/***************************************************************************************************
 * Copyright (c) 2025 - 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 * list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 * contributors may be used to endorse or promote products derived from
 * this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 **************************************************************************************************/
//
// Project-owned fork of 3rdparty/cutlass/include/cutlass/gemm/collective/sm120_blockscaled_mma_tma.hpp
// (CUTLASS's real SM120 block-scaled dense-GEMM mainloop -- TMA double-buffered, warp-specialized,
// confirmed via research to be the only implementation this problem's CollectiveBuilder resolves to,
// see /home/brian/.claude/plans/mutable-soaring-pascal.md).
//
// Stage 1a: this is a byte-for-byte-equivalent copy (only the DispatchPolicy tag in the template
// header differs, so it specializes on MainloopSm120TmaWarpSpecializedBlockScaledMixed instead of
// CUTLASS's own tag -- see dispatch_policy_mixed.hpp) with ZERO functional changes. Its only job
// right now is to prove the fork-and-substitute-DispatchPolicy mechanism (mixed_nvfp4_gemm.cu
// reuses cutlass::gemm::collective::CollectiveBuilder for all type derivation, then swaps in our
// DispatchPolicy so this specialization gets selected instead of the vendored one) produces
// results identical to the unforked src/nvfp4_gemm.cu, before Stage 1b adds any dispatch logic to
// gemm_kblock/copy_kblock. Do not edit this file to "improve" it independent of that mechanism
// check -- once parity is confirmed, changes here should only be the Stage 1b mixed-dispatch work.

#pragma once

#include "cutlass/cutlass.h"
#include "cutlass/gemm/gemm.h"
#include "cutlass/pipeline/pipeline.hpp"
#include "cutlass/gemm/dispatch_policy.hpp"
#include "cutlass/detail/dependent_false.hpp"
#include "cutlass/detail/sm100_blockscaled_layout.hpp"
#include "cutlass/trace.h"
#include "cutlass/numeric_types.h"

#include "cute/arch/cluster_sm90.hpp"
#include "cute/arch/copy_sm90.hpp"
#include "cute/atom/mma_atom.hpp"

#include "collective/mma_sm120_mixed.hpp"
#include "cute/algorithm/functional.hpp"
#include "cute/algorithm/gemm.hpp"
#include "cute/numeric/arithmetic_tuple.hpp"

#include "dispatch_policy_mixed.hpp"

/////////////////////////////////////////////////////////////////////////////////////////////////

namespace cutlass::gemm::collective {
using namespace cute;

// How many MMA atoms share one format flag, i.e. the size of a format granule in atoms. The atom
// is m16n8k64, so a granule is (kMixedAAtomsPerGranule * 16) rows of A by
// (kMixedBAtomsPerGranule * 8) columns of B, over one k_tile of K.
//
// The defaults give a symmetric 32-row x 32-column granule. A=2/B=4 is the cheap symmetric point;
// A=1/B=2 gives the finest granule the hardware permits (16x16, since the atom's M is 16) at the
// cost of 64 specialized arms instead of 8. See the table in mma_sm120_mixed.hpp.
#ifndef MIXFP4_A_ATOMS_PER_GRANULE
#define MIXFP4_A_ATOMS_PER_GRANULE 2
#endif
#ifndef MIXFP4_B_ATOMS_PER_GRANULE
#define MIXFP4_B_ATOMS_PER_GRANULE 4
#endif

// -DMIXFP4_PTX=1 replaces the C++ pattern dispatch with generated inline-PTX statements, one per
// dispatch group per k_block, each opening with a brx.idx over that group's format flags. This is
// the only path that reaches the hardware floor (16 rows x 8 columns x 64 K), because the C++
// path's dispatch has to enclose a whole k_tile and its arm count is capped by cicc outlining.
//
// It is NOT the fast path: a dispatch inside the k_tile body costs ~90 cycles because it stops
// ptxas interleaving the next k_block's LDSM loads with this k_block's MMAs. See section 5 of
// docs/mixed_nvfp4_report.md for the measured curve. Use it when granularity matters more than
// throughput.
//
// The granule is fixed by the generator, so the tagging macros are taken from the generated
// header rather than restated here.
#if defined(MIXFP4_PTX_16X16) && MIXFP4_PTX_16X16   // deprecated spelling
#undef  MIXFP4_PTX
#define MIXFP4_PTX 1
#endif
#if defined(MIXFP4_PTX) && MIXFP4_PTX
#include "collective/mixed_mma_generated.hpp"
#undef  MIXFP4_A_ATOMS_PER_GRANULE
#define MIXFP4_A_ATOMS_PER_GRANULE MIXFP4_GEN_A_ATOMS
#undef  MIXFP4_B_ATOMS_PER_GRANULE
#define MIXFP4_B_ATOMS_PER_GRANULE MIXFP4_GEN_B_ATOMS
#define MIXFP4_K_GRANULE           MIXFP4_GEN_K_GRANULE
#endif

// -DMIXFP4_BLOB=1 keeps the cheap per-k_tile C++ dispatch but emits each k_block's MMAs as one
// opaque generated blob (scripts/gen_mixed_mma_blob.py). Fewer inline-asm statements per k_tile
// body moves cicc's outlining cliff from 8 arms to between 32 and 64, so the cheap dispatch can
// carry a finer granule -- at K=128, since the dispatch still encloses the whole k_tile. Set
// -DMIXFP4_A/B_ATOMS_PER_GRANULE to match whatever the generator was run with.
#if defined(MIXFP4_BLOB) && MIXFP4_BLOB
#include "collective/mixed_mma_blob_generated.hpp"
// Joint-K rides on the blob path (it needs the arms to stay inlined) and takes the K granule down
// to one k_block while leaving the dispatch outside the k_tile body. The host tagging follows.
#if defined(MIXFP4_JOINT_K) && MIXFP4_JOINT_K
#define MIXFP4_K_GRANULE 64
#endif
// Joint-K-B: only B's K granule drops to a k_block; A stays at the k_tile.
#if defined(MIXFP4_JOINT_KB) && MIXFP4_JOINT_KB
#define MIXFP4_K_GRANULE_B 64
// NOT defaulted on here, unlike joint-K-A. Measured at 16 arms with A pinned to E2M1:
// 1101.0 un-pipelined against 1083.9 pipelined. Same signature as the 16x16x64 path -- this
// configuration is issue-bound, so taking latency off the branch costs register lifetime to
// hide something that was not on the critical path. Available as -DMIXFP4_PIPE_FLAGS=1.
#endif
// Joint-K-A: the mirror image -- only A's K granule drops to a k_block, B stays at the k_tile.
// This is what a 16 rows x 64 K granule on A costs: 2*kAGran + kBGran bits. With A at one atom
// (kAGran=2) and B coarsened to the warp's whole 64-column footprint (kBGran=1) that is 5 bits,
// so 32 arms -- the most the blob path inlines.
#if defined(MIXFP4_JOINT_KA) && MIXFP4_JOINT_KA
#define MIXFP4_K_GRANULE_A 64
// Joint-K-A is the one path with a flag that cannot come from registers, so it is the one path
// that benefits from computing the next k_tile's arm index a k_block early. Strictly better
// everywhere measured (+2.0 points at 4096^3); -DMIXFP4_PIPE_FLAGS=0 restores the naive read.
#ifndef MIXFP4_PIPE_FLAGS
#define MIXFP4_PIPE_FLAGS 1
#endif
#endif
// Split-K: one dispatch per k_block, but -- unlike the historical "in-body" dispatch that cost
// ~20 points -- each arm contains that k_block's smem->rmem copies AS WELL AS its MMAs.
//
// That distinction is the whole point. The measured cost of a per-k_block dispatch was never the
// branch; it was `short_scoreboard` + `mio_throttle` stalls from LDSMs bunching, because with the
// copies OUTSIDE the branch ptxas can no longer sink them in among the MMAs. Putting the copy
// inside the arm restores the interleave within each arm, where ptxas is free to schedule again.
//
// The prize is arm count: a k_block needs only kAGran + kBGran bits, so a 16-row x 64-K granule on
// A costs 8 arms per dispatch rather than the 32 that joint-K needs -- and it gives B a 64-element
// K granule for free.
#if defined(MIXFP4_SPLIT_K) && MIXFP4_SPLIT_K
#define MIXFP4_K_GRANULE 64
#endif
#endif

// TIMING PROBE ONLY -- computes wrong numbers by construction.
//
// Replaces the dispatch index with a warp-uniform value derived from the LOOP COUNTER, costing
// about one instruction. The flag reads are gone but the branch still executes every k_tile and
// still cannot be hoisted.
//
// The counter matters. A loop-INVARIANT index (blockIdx) lets ptxas unswitch the loop -- hoist the
// branch out and put the k-loop inside each arm -- and the probe then measures the per-CTA
// structure instead of an in-loop branch. That showed up as 1211.9 TFLOP/s against a 1191.0
// no-dispatch ceiling, i.e. faster than having no branch at all, which is the tell.
#if defined(MIXFP4_FAKE_INDEX) && MIXFP4_FAKE_INDEX
#define MIXFP4_IX(expr, narms) (uint32_t(k_tile_count) & uint32_t((narms) - 1))
#else
#define MIXFP4_IX(expr, narms) (expr)
#endif

namespace mixfp4_detail {

// Compile-time dispatch on a runtime pattern index, as a balanced binary search so the cost is
// log2(arms) compares rather than a linear chain. A plain `switch` would be nicer but nvcc turns
// dense switches back into branch trees here anyway, and a linear if-chain over 64 arms is not
// acceptable. Each leaf is a whole specialized k_tile body -- far too large, and containing
// barriers, so ptxas leaves these as real branches rather than if-converting them.
template <int Lo, int Hi, class Body>
CUTLASS_DEVICE void
dispatch_pattern(uint32_t pattern, Body&& body) {
  if constexpr (Lo == Hi) {
    body(cute::C<Lo>{});
  }
  else {
    constexpr int Mid = Lo + (Hi - Lo) / 2;
    if (pattern <= uint32_t(Mid)) { dispatch_pattern<Lo, Mid>(pattern, body); }
    else                          { dispatch_pattern<Mid + 1, Hi>(pattern, body); }
  }
}

// Pattern bit layout: A granule flags occupy bits [0, AGranules), B granule flags follow in
// bits [AGranules, AGranules + BGranules).
template <int AGranules, int AAtomsPerGranule>
CUTLASS_DEVICE constexpr uint32_t a_flag_of_atom(uint32_t pattern, int m_atom) {
  return (pattern >> (m_atom / AAtomsPerGranule)) & 1u;
}
template <int AGranules, int BAtomsPerGranule>
CUTLASS_DEVICE constexpr uint32_t b_flag_of_atom(uint32_t pattern, int n_atom) {
  return (pattern >> (AGranules + n_atom / BAtomsPerGranule)) & 1u;
}

} // namespace mixfp4_detail

/////////////////////////////////////////////////////////////////////////////////////////////////

template <
  int Stages,
  int SchedulerPipelineStageCount,
  class ClusterShape,
  class KernelScheduleType,
  class TileShape_,
  class ElementPairA_,
  class StridePairA_,
  class ElementPairB_,
  class StridePairB_,
  class TiledMma_,
  class GmemTiledCopyPairA_,
  class SmemLayoutAtomsA_,
  class SmemCopyAtomsA_,
  class TransformA_,
  class GmemTiledCopyPairB_,
  class SmemLayoutAtomsB_,
  class SmemCopyAtomsB_,
  class TransformB_>
struct CollectiveMma<
    MainloopSm120TmaWarpSpecializedBlockScaledMixed<Stages, SchedulerPipelineStageCount, ClusterShape, KernelScheduleType>,
    TileShape_,
    ElementPairA_,
    StridePairA_,
    ElementPairB_,
    StridePairB_,
    TiledMma_,
    GmemTiledCopyPairA_,
    SmemLayoutAtomsA_,
    SmemCopyAtomsA_,
    TransformA_,
    GmemTiledCopyPairB_,
    SmemLayoutAtomsB_,
    SmemCopyAtomsB_,
    TransformB_> {
  //
  // Type Aliases
  //
  using DispatchPolicy = MainloopSm120TmaWarpSpecializedBlockScaledMixed<Stages, SchedulerPipelineStageCount, ClusterShape, KernelScheduleType>;
  using TileShape = TileShape_;
  using ElementPairA = ElementPairA_;
  using ElementPairB = ElementPairB_;
  using StridePairA = StridePairA_;
  using StridePairB = StridePairB_;

  static_assert(cute::is_same_v<remove_cvref_t<decltype(get<1>(ElementPairA{}))>,
                                remove_cvref_t<decltype(get<1>(ElementPairB{}))>>, "SFA and SFB data types should be the same");

  using RuntimeDataTypeA = void*;
  using RuntimeDataTypeB = void*;

   // A and B matrices
  using ElementA = remove_cvref_t<decltype(get<0>(ElementPairA{}))>;
  using StrideA  = remove_cvref_t<decltype(get<0>(StridePairA{}))>;

  using ElementB = remove_cvref_t<decltype(get<0>(ElementPairB{}))>;
  using StrideB  = remove_cvref_t<decltype(get<0>(StridePairB{}))>;

  // SFA and SFB
  using ElementSF = remove_cvref_t<decltype(get<1>(ElementPairA{}))>;
  using LayoutSFA = remove_cvref_t<decltype(get<1>(StridePairA{}))>;
  using LayoutSFB = remove_cvref_t<decltype(get<1>(StridePairB{}))>;

  using ArrayElementA = ElementA;
  using ArrayElementB = ElementB;

  using TiledMma = TiledMma_;
  using CtaShape_MNK = decltype(shape_div(TileShape{}, ClusterShape{}));
  using ElementAccumulator = typename TiledMma::ValTypeC;

  static constexpr int SFVecSize = TiledMma::Traits::SFVecSize;
  using Sm1xxBlkScaledConfig = cutlass::detail::Sm1xxBlockScaledConfig<SFVecSize>;

  // Gmem copies
  using GmemTiledCopyPairA = GmemTiledCopyPairA_;
  using GmemTiledCopyPairB = GmemTiledCopyPairB_;
  using GmemTiledCopyA    = remove_cvref_t<decltype(get<0>(GmemTiledCopyPairA{}))>;
  using GmemTiledCopySFA  = remove_cvref_t<decltype(get<1>(GmemTiledCopyPairA{}))>;
  using GmemTiledCopyB    = remove_cvref_t<decltype(get<0>(GmemTiledCopyPairB{}))>;
  using GmemTiledCopySFB  = remove_cvref_t<decltype(get<1>(GmemTiledCopyPairB{}))>;

  // Smem copies
  using SmemLayoutAtomsA = SmemLayoutAtomsA_;
  using SmemLayoutAtomsB = SmemLayoutAtomsB_;

  using SmemLayoutAtomA   = remove_cvref_t<decltype(get<0>(SmemLayoutAtomsA{}))>;
  using SmemLayoutAtomSFA = remove_cvref_t<decltype(get<1>(SmemLayoutAtomsA{}))>;
  using SmemLayoutAtomB   = remove_cvref_t<decltype(get<0>(SmemLayoutAtomsB{}))>;
  using SmemLayoutAtomSFB = remove_cvref_t<decltype(get<1>(SmemLayoutAtomsB{}))>;

  using SmemCopyAtomsA =  SmemCopyAtomsA_;
  using SmemCopyAtomsB =  SmemCopyAtomsB_;

  using SmemCopyAtomA   = remove_cvref_t<decltype(get<0>(SmemCopyAtomsA{}))>;
  using SmemCopyAtomSFA = remove_cvref_t<decltype(get<1>(SmemCopyAtomsA{}))>;

  using SmemCopyAtomB   = remove_cvref_t<decltype(get<0>(SmemCopyAtomsB{}))>;
  using SmemCopyAtomSFB = remove_cvref_t<decltype(get<1>(SmemCopyAtomsB{}))>;

  using TransformA = TransformA_;
  using TransformB = TransformB_;

  using ArchTag = typename DispatchPolicy::ArchTag;

  static constexpr int ThreadCount = size(TiledMma{});

  using MainloopPipeline = cutlass::PipelineTmaAsync<DispatchPolicy::Stages>;

  using PipelineParams = typename MainloopPipeline::Params;
  using PipelineState  = typename cutlass::PipelineState<DispatchPolicy::Stages>;

  // One threads per CTA are producers (1 for operand tile)
  static constexpr int NumProducerThreadEvents = 1;

  static_assert(rank(SmemLayoutAtomA{}) == 2, "SmemLayoutAtom must be rank 2 (M/N, K)");
  static_assert((size<0>(TileShape{}) % size<0>(SmemLayoutAtomA{})) == 0, "SmemLayoutAtom must evenly divide tile shape.");
  static_assert((size<2>(TileShape{}) % size<1>(SmemLayoutAtomA{})) == 0, "SmemLayoutAtom must evenly divide tile shape.");

  static_assert(rank(SmemLayoutAtomB{}) == 2, "SmemLayoutAtom must be rank 2 (M/N, K)");
  static_assert((size<1>(TileShape{}) % size<0>(SmemLayoutAtomB{})) == 0, "SmemLayoutAtom must evenly divide tile shape.");
  static_assert((size<2>(TileShape{}) % size<1>(SmemLayoutAtomB{})) == 0, "SmemLayoutAtom must evenly divide tile shape.");

  static_assert(not cute::is_void_v<SmemCopyAtomA>,
    "SM120 mainloop must specify a copy atom for A operand smem->rmem reads.");
  static_assert(not cute::is_void_v<SmemCopyAtomB>,
    "SM120 mainloop must specify a copy atom for B operand smem->rmem reads.");

  // Tile along modes in a way that maximizes the TMA box size.
  using SmemLayoutA = decltype(tile_to_shape(
      SmemLayoutAtomA{},
      make_shape(shape<0>(TileShape{}), shape<2>(TileShape{}), Int<DispatchPolicy::Stages>{}),
      conditional_t< ::cutlass::gemm::detail::is_major<0,StrideA>(), Step<_2,_1,_3>, Step<_1,_2,_3>>{}));
  using SmemLayoutB = decltype(tile_to_shape(
      SmemLayoutAtomB{},
      make_shape(shape<1>(TileShape{}), shape<2>(TileShape{}), Int<DispatchPolicy::Stages>{}),
      conditional_t< ::cutlass::gemm::detail::is_major<0,StrideB>(), Step<_2,_1,_3>, Step<_1,_2,_3>>{}));

  // SmemLayoutAtomSFA and SmemLayoutAtomSFB are for whole CTA tiles. We add the number of pipeline stages here.
  // The number of pipeline stages is the same as the number of pipeline stages from AB Load <-> MainLoop
  using SmemLayoutSFA = decltype(make_layout(
    append(shape(SmemLayoutAtomSFA{}), Int<DispatchPolicy::Stages>{}),
    append(stride(SmemLayoutAtomSFA{}), size(filter_zeros(SmemLayoutAtomSFA{})))
  ));

  using SmemLayoutSFB_ = decltype(make_layout(
    append(shape(SmemLayoutAtomSFB{}), Int<DispatchPolicy::Stages>{}),
    append(stride(SmemLayoutAtomSFB{}), size(filter_zeros(SmemLayoutAtomSFB{})))
  ));

  using TileShapeSFB = cute::conditional_t<size<1>(TileShape{}) < 128,
    decltype(cute::make_shape(
      shape<0>(TileShape{}),
      Int<128>{},
      shape<2>(TileShape{}))),
    TileShape>;

  using SmemLayoutSFB = cute::conditional_t<size<1>(TileShape{}) < 128,
    decltype(cute::logical_divide(SmemLayoutSFB_{}, select<1,2>(TileShape{}))),
    SmemLayoutSFB_>;

  static_assert(rank(SmemLayoutA{}) == 3, "Smem layout must be rank 3.");
  static_assert(rank(SmemLayoutB{}) == 3, "Smem layout must be rank 3.");

  static_assert(DispatchPolicy::Stages >= 2, "Specialization requires Stages set to value 2 or more.");
  static_assert(not cute::is_base_of<cute::GMMA::DescriptorIterator, typename TiledMma::FrgTypeA>::value &&
                not cute::is_base_of<cute::GMMA::DescriptorIterator, typename TiledMma::FrgTypeB>::value,
                "MMA atom must source both A and B operands from rmem for this mainloop.");
  static_assert(cute::is_same_v<GmemTiledCopyA, SM90_TMA_LOAD>, "GmemTiledCopy - invalid SM90 TMA copy atom specified.");
  static_assert(cute::is_same_v<GmemTiledCopyB, SM90_TMA_LOAD>, "GmemTiledCopy - invalid SM90 TMA copy atom specified.");

  static constexpr bool IsF8F6F4 = detail::is_sm120_f8f6f4<TiledMma, ElementA, ElementB>();

  // For all other types, cast to size equivalent uint type to avoid any rounding by TMA.
  using TmaInternalElementA = cute::conditional_t<not IsF8F6F4,
                                                  ElementA,
                              cute::conditional_t<cute::is_same_v<ElementA, cutlass::float_e2m1_t>,
                                                  cutlass::detail::float_e2m1_unpacksmem_t,
                              cute::conditional_t<cute::is_same_v<ElementA, cutlass::float_e2m3_t>,
                                                cutlass::detail::float_e2m3_unpacksmem_t,
                              cute::conditional_t<cute::is_same_v<ElementA, cutlass::float_e3m2_t>,
                                                cutlass::detail::float_e3m2_unpacksmem_t,
                                                uint_bit_t<sizeof_bits_v<ElementA>>>>>>;

  using TmaInternalElementB = cute::conditional_t<not IsF8F6F4,
                                                  ElementB,
                              cute::conditional_t<cute::is_same_v<ElementB, cutlass::float_e2m1_t>,
                                                  cutlass::detail::float_e2m1_unpacksmem_t,
                              cute::conditional_t<cute::is_same_v<ElementB, cutlass::float_e2m3_t>,
                                                cutlass::detail::float_e2m3_unpacksmem_t,
                              cute::conditional_t<cute::is_same_v<ElementB, cutlass::float_e3m2_t>,
                                                cutlass::detail::float_e3m2_unpacksmem_t,
                                                uint_bit_t<sizeof_bits_v<ElementB>>>>>>;

  using TmaInternalElementSF = ElementSF;

  using SmemAllocTypeA = cute::conditional_t<IsF8F6F4, uint8_t, typename TiledMma::ValTypeA>;
  using SmemAllocTypeB = cute::conditional_t<IsF8F6F4, uint8_t, typename TiledMma::ValTypeB>;

  // Set the bytes transferred in this TMA transaction (may involve multiple issues)
  static constexpr uint32_t TmaTransactionBytesMK = static_cast<uint32_t>(
    cutlass::bits_to_bytes(cosize(take<0,2>(SmemLayoutSFA{})) * cute::sizeof_bits_v<ElementSF>) +
    cutlass::bits_to_bytes(size(take<0,2>(SmemLayoutA{})) * sizeof_bits<ElementA>::value));

  static constexpr uint32_t TmaTransactionBytesNK = static_cast<uint32_t>(
    cutlass::bits_to_bytes(cosize(take<0,2>(SmemLayoutSFB{})) * cute::sizeof_bits_v<ElementSF>) +
    cutlass::bits_to_bytes(size(take<0,2>(SmemLayoutB{})) * sizeof_bits<ElementB>::value));

  static constexpr uint32_t TmaTransactionBytes = TmaTransactionBytesMK + TmaTransactionBytesNK;

  struct SharedStorage {
    struct TensorStorage : cute::aligned_struct<128, _0> {
      alignas(1024) cute::ArrayEngine<SmemAllocTypeA, cute::cosize_v<SmemLayoutA>> smem_A;
      alignas(1024) cute::ArrayEngine<SmemAllocTypeB, cute::cosize_v<SmemLayoutB>> smem_B;
      alignas(16)   cute::ArrayEngine<ElementSF, cute::cosize_v<SmemLayoutSFA>> smem_SFA;
      alignas(16)   cute::ArrayEngine<ElementSF, cute::cosize_v<SmemLayoutSFB>> smem_SFB;
    } tensors;
    using PipelineStorage = typename MainloopPipeline::SharedStorage;
    alignas(16) PipelineStorage pipeline_storage;
  };

  using TensorStorage = typename SharedStorage::TensorStorage;
  using PipelineStorage = typename SharedStorage::PipelineStorage;

  // Host side kernel arguments
  struct Arguments {
    ElementA const* ptr_A{nullptr};
    StrideA dA{};
    ElementB const* ptr_B{nullptr};
    StrideB dB{};
    ElementSF const* ptr_SFA{nullptr};
    LayoutSFA layout_SFA{};
    ElementSF const* ptr_SFB{nullptr};
    LayoutSFB layout_SFB{};
  };

  // Device side kernel params
  struct Params {
    // Assumption: StrideA is congruent with Problem_MK
    using TMA_A = decltype(make_tma_copy(
        GmemTiledCopyA{},
        make_tensor(recast_ptr<TmaInternalElementA>(nullptr), repeat_like(StrideA{}, int32_t(0)), StrideA{}),
        SmemLayoutA{}(_,_,cute::Int<0>{}),
        make_shape(shape<0>(TileShape{}), shape<2>(TileShape{})),
        _1{}));  // No programmatic multicast
    // Assumption: StrideB is congruent with Problem_NK
    using TMA_B = decltype(make_tma_copy(
        GmemTiledCopyB{},
        make_tensor(recast_ptr<TmaInternalElementB>(nullptr), repeat_like(StrideB{}, int32_t(0)), StrideB{}),
        SmemLayoutB{}(_,_,cute::Int<0>{}),
        make_shape(shape<1>(TileShape{}), shape<2>(TileShape{})),
        _1{}));  // No programmatic multicast

    using TMA_SFA = decltype(make_tma_copy<uint16_t>(
        GmemTiledCopySFA{},
        make_tensor(static_cast<ElementSF const*>(nullptr), LayoutSFA{}),
        SmemLayoutSFA{}(_,_,cute::Int<0>{}),
        make_shape(shape<0>(TileShape{}), shape<2>(TileShape{})),
        _1{}));  // No programmatic multicast


    using TMA_SFB = decltype(make_tma_copy<uint16_t>(
        GmemTiledCopySFB{},
        make_tensor(static_cast<ElementSF const*>(nullptr), LayoutSFB{}),
        SmemLayoutSFB{}(_,_,cute::Int<0>{}),
        make_shape(shape<1>(TileShapeSFB{}), shape<2>(TileShapeSFB{})),
        _1{}));  // No programmatic multicast

    TMA_A tma_load_a;
    TMA_B tma_load_b;
    TMA_SFA tma_load_sfa;
    TMA_SFB tma_load_sfb;
    LayoutSFA layout_SFA;
    LayoutSFB layout_SFB;
    uint32_t tma_transaction_bytes = TmaTransactionBytes;
    uint32_t tma_transaction_bytes_mk = TmaTransactionBytesMK;
    uint32_t tma_transaction_bytes_nk = TmaTransactionBytesNK;
  };

  //
  // Methods
  //

  template <class ProblemShape>
  static constexpr Params
  to_underlying_arguments(ProblemShape const& problem_shape, Arguments const& args, void* workspace) {
    (void) workspace;

    // Optionally append 1s until problem shape is rank-4 (MNKL), in case it is only rank-3 (MNK)
    auto problem_shape_MNKL = append<4>(problem_shape, 1);
    auto [M, N, K, L] = problem_shape_MNKL;

    auto ptr_A = recast_ptr<TmaInternalElementA>(args.ptr_A);
    auto ptr_B = recast_ptr<TmaInternalElementB>(args.ptr_B);

    Tensor tensor_a = make_tensor(ptr_A, make_layout(make_shape(M,K,L), args.dA));
    Tensor tensor_b = make_tensor(ptr_B, make_layout(make_shape(N,K,L), args.dB));

    Tensor tensor_sfa = make_tensor(args.ptr_SFA, args.layout_SFA);
    Tensor tensor_sfb = make_tensor(args.ptr_SFB, args.layout_SFB);

    typename Params::TMA_A tma_load_a = make_tma_copy(
        GmemTiledCopyA{},
        tensor_a,
        SmemLayoutA{}(_,_,cute::Int<0>{}),
        make_shape(shape<0>(TileShape{}), shape<2>(TileShape{})),
        _1{}); // No programmatic multicast
    typename Params::TMA_B tma_load_b = make_tma_copy(
        GmemTiledCopyB{},
        tensor_b,
        SmemLayoutB{}(_,_,cute::Int<0>{}),
        make_shape(shape<1>(TileShape{}), shape<2>(TileShape{})),
        _1{}); // No programmatic multicast

    typename Params::TMA_SFA tma_load_sfa = make_tma_copy<uint16_t>(
        GmemTiledCopySFA{},
        tensor_sfa,
        SmemLayoutSFA{}(_,_,cute::Int<0>{}),
        make_shape(shape<0>(TileShape{}), shape<2>(TileShape{})),
        _1{}); // No programmatic multicast

    typename Params::TMA_SFB tma_load_sfb = make_tma_copy<uint16_t>(
        GmemTiledCopySFB{},
        tensor_sfb,
        SmemLayoutSFB{}(_,_,cute::Int<0>{}),
        make_shape(shape<1>(TileShapeSFB{}), shape<2>(TileShapeSFB{})),
        _1{}); // No programmatic multicast

    return {
      tma_load_a,
      tma_load_b,
      tma_load_sfa,
      tma_load_sfb,
      args.layout_SFA,
      args.layout_SFB,
      TmaTransactionBytes,
      TmaTransactionBytesMK,
      TmaTransactionBytesNK
    };
  }

  template<class ProblemShape>
  CUTLASS_HOST_DEVICE static bool
  can_implement(
      ProblemShape const& problem_shape,
      [[maybe_unused]] Arguments const& args) {
    auto problem_shape_MNKL = append<4>(problem_shape, 1);
    auto [M, N, K, L] = problem_shape_MNKL;

    constexpr int tma_alignment_bits_A = cutlass::detail::get_input_alignment_bits<ElementA, IsF8F6F4>();
    constexpr int tma_alignment_bits_B = cutlass::detail::get_input_alignment_bits<ElementB, IsF8F6F4>();

    bool implementable = true;
    constexpr int min_tma_aligned_elements_A = tma_alignment_bits_A / cutlass::sizeof_bits<ElementA>::value;
    implementable = implementable && cutlass::detail::check_alignment<min_tma_aligned_elements_A>(cute::make_shape(M,K,L), StrideA{});
    constexpr int min_tma_aligned_elements_B = tma_alignment_bits_B / cutlass::sizeof_bits<ElementB>::value;
    implementable = implementable && cutlass::detail::check_alignment<min_tma_aligned_elements_B>(cute::make_shape(N,K,L), StrideB{});

    if (!implementable) {
      CUTLASS_TRACE_HOST("  CAN IMPLEMENT: Problem Size doesn't meet the minimum alignment requirements for TMA.\n");
    }
    return implementable;
  }

  /// Issue Tma Descriptor Prefetch -- ideally from a single thread for best performance
  CUTLASS_DEVICE
  static void prefetch_tma_descriptors(Params const& params) {
    cute::prefetch_tma_descriptor(params.tma_load_a.get_tma_descriptor());
    cute::prefetch_tma_descriptor(params.tma_load_b.get_tma_descriptor());
    cute::prefetch_tma_descriptor(params.tma_load_sfa.get_tma_descriptor());
    cute::prefetch_tma_descriptor(params.tma_load_sfb.get_tma_descriptor());
  }

  // Temporary adhoc partitioning for scaling factors.
  template <class SFATensor, class Atom, class TiledThr, class TiledPerm>
  CUTE_HOST_DEVICE constexpr
  auto
  thrfrg_SFA(SFATensor&& sfatensor, TiledMMA<Atom, TiledThr, TiledPerm>& mma)
  {
    CUTE_STATIC_ASSERT_V(rank(sfatensor) >= Int<2>{});

    using AtomShape_MNK  = typename Atom::Shape_MNK;
    using AtomLayoutSFA_TV = typename Atom::Traits::SFALayout;

    auto permutation_mnk = TiledPerm{};
    auto thr_layout_vmnk = mma.get_thr_layout_vmnk();

    // Reorder the tensor for the TiledAtom
    auto t_tile = make_tile(get<0>(permutation_mnk),
                            get<2>(permutation_mnk));
    auto t_tensor = logical_divide(sfatensor, t_tile);                 // (PermM,PermK)

    // Tile the tensor for the Atom
    auto a_tile = make_tile(make_layout(size<0>(AtomShape_MNK{})),
                            make_layout(size<2>(AtomShape_MNK{})));
    auto a_tensor = zipped_divide(t_tensor, a_tile);                 // ((AtomM,AtomK),(RestM,RestK))

    // Transform the Atom mode from (M,K) to (Thr,Val)
    auto tv_tensor = a_tensor.compose(AtomLayoutSFA_TV{},_);           // ((ThrV,FrgV),(RestM,RestK))

    // Tile the tensor for the Thread
    auto thr_tile = make_tile(_,
                              make_tile(make_layout(size<1>(thr_layout_vmnk)),
                                        make_layout(size<3>(thr_layout_vmnk))));
    auto thr_tensor = zipped_divide(tv_tensor, thr_tile);            // ((ThrV,(ThrM,ThrK)),(FrgV,(RestM,RestK)))

    return thr_tensor;
  }

  template <class SFBTensor, class Atom, class TiledThr, class TiledPerm>
  CUTE_HOST_DEVICE constexpr
  auto
  thrfrg_SFB(SFBTensor&& sfbtensor, TiledMMA<Atom, TiledThr, TiledPerm>& mma)
  {
    CUTE_STATIC_ASSERT_V(rank(sfbtensor) >= Int<2>{});

    using AtomShape_MNK  = typename Atom::Shape_MNK;
    using AtomLayoutSFB_TV = typename Atom::Traits::SFBLayout;

    auto permutation_mnk = TiledPerm{};
    auto thr_layout_vmnk = mma.get_thr_layout_vmnk();

    // Reorder the tensor for the TiledAtom
    auto t_tile = make_tile(get<1>(permutation_mnk),
                            get<2>(permutation_mnk));
    auto t_tensor = logical_divide(sfbtensor, t_tile);                 // (PermN,PermK)

    // Tile the tensor for the Atom
    auto a_tile = make_tile(make_layout(size<1>(AtomShape_MNK{})),
                            make_layout(size<2>(AtomShape_MNK{})));
    auto a_tensor = zipped_divide(t_tensor, a_tile);                 // ((AtomN,AtomK),(RestN,RestK))

    // Transform the Atom mode from (M,K) to (Thr,Val)
    auto tv_tensor = a_tensor.compose(AtomLayoutSFB_TV{},_);           // ((ThrV,FrgV),(RestN,RestK))

    // Tile the tensor for the Thread
    auto thr_tile = make_tile(_,
                              make_tile(make_layout(size<2>(thr_layout_vmnk)),
                                        make_layout(size<3>(thr_layout_vmnk))));
    auto thr_tensor = zipped_divide(tv_tensor, thr_tile);            // ((ThrV,(ThrN,ThrK)),(FrgV,(RestN,RestK)))
    return thr_tensor;
  }

  template <class SFATensor, class ThrMma>
  CUTE_HOST_DEVICE constexpr
  auto
  partition_fragment_SFA(SFATensor&& sfatensor, ThrMma& thread_mma)
  {
    using ValTypeSF = typename ThrMma::Atom::Traits::ValTypeSF;
    auto thr_tensor = make_tensor(static_cast<SFATensor&&>(sfatensor).data(), thrfrg_SFA(sfatensor.layout(),thread_mma));
    auto thr_vmnk = thread_mma.thr_vmnk_;
    auto thr_vmk = make_coord(get<0>(thr_vmnk), make_coord(get<1>(thr_vmnk), get<3>(thr_vmnk)));
    auto partition_SFA =  thr_tensor(thr_vmk, make_coord(_, repeat<rank<1,1>(thr_tensor)>(_)));
    return make_fragment_like<ValTypeSF>(partition_SFA);
  }

  template <class SFBTensor, class ThrMma>
  CUTE_HOST_DEVICE constexpr
  auto
  partition_fragment_SFB(SFBTensor&& sfbtensor, ThrMma& thread_mma)
  {
    using ValTypeSF = typename ThrMma::Atom::Traits::ValTypeSF;
    auto thr_tensor = make_tensor(static_cast<SFBTensor&&>(sfbtensor).data(), thrfrg_SFB(sfbtensor.layout(),thread_mma));
    auto thr_vmnk = thread_mma.thr_vmnk_;
    auto thr_vnk = make_coord(get<0>(thr_vmnk), make_coord(get<2>(thr_vmnk), get<3>(thr_vmnk)));
    auto partition_SFB =  thr_tensor(thr_vnk, make_coord(_, repeat<rank<1,1>(thr_tensor)>(_)));
    return make_fragment_like<ValTypeSF>(partition_SFB);
  }

  template<class TiledMma>
  CUTE_HOST_DEVICE constexpr
  auto
  get_layoutSFA_TV(TiledMma& mma)
  {
    // (M,K) -> (M,K)
    auto tile_shape_mnk = tile_shape(mma);
    auto ref_A = make_layout(make_shape(size<0>(tile_shape_mnk), size<2>(tile_shape_mnk)));
    auto thr_layout_vmnk = mma.get_thr_layout_vmnk();

    // (ThrV,(ThrM,ThrK)) -> (ThrV,(ThrM,ThrN,ThrK))
    auto atile = make_tile(_,
                          make_tile(make_layout(make_shape (size<1>(thr_layout_vmnk), size<2>(thr_layout_vmnk)),
                                                make_stride(               Int<1>{} ,                Int<0>{} )),
                                    _));

    // thr_idx -> (ThrV,ThrM,ThrN,ThrK)
    auto thridx_2_thrid = right_inverse(thr_layout_vmnk);
    // (thr_idx,val) -> (M,K)
    return thrfrg_SFA(ref_A, mma).compose(atile, _).compose(thridx_2_thrid, _);
  }

  template<class TiledMma>
  CUTE_HOST_DEVICE constexpr
  auto
  get_layoutSFB_TV(TiledMma& mma)
  {
    // (N,K) -> (N,K)
    auto tile_shape_mnk = tile_shape(mma);
    auto ref_B = make_layout(make_shape(size<1>(tile_shape_mnk), size<2>(tile_shape_mnk)));
    auto thr_layout_vmnk = mma.get_thr_layout_vmnk();

    // (ThrV,(ThrM,ThrK)) -> (ThrV,(ThrM,ThrN,ThrK))
    auto btile = make_tile(_,
                          make_tile(make_layout(make_shape (size<1>(thr_layout_vmnk), size<2>(thr_layout_vmnk)),
                                                make_stride(               Int<0>{} ,                Int<1>{} )),
                                    _));

    // thr_idx -> (ThrV,ThrM,ThrN,ThrK)
    auto thridx_2_thrid = right_inverse(thr_layout_vmnk);
    // (thr_idx,val) -> (M,K)
    return thrfrg_SFB(ref_B, mma).compose(btile, _).compose(thridx_2_thrid, _);
  }

  /// Set up the data needed by this collective for load and mma.
  /// Returns a tuple of tensors. The collective and the kernel layer have the contract
  /// Returned tuple must contain at least two elements, with the first two elements being:
  /// gA_mkl - The tma tensor, A after a local tile so it has shape  (BLK_M,BLK_K,m,k,l)
  /// gB_nkl - The tma tensor, B after a local tile so it has shape  (BLK_N,BLK_K,n,k,l)
  /// The rest of the tensors can be specified as needed by this collective.
  template <class ProblemShape_MNKL>
  CUTLASS_DEVICE auto
  load_init(ProblemShape_MNKL const& problem_shape_MNKL, Params const& params) const {
    using X = Underscore;
    // Separate out problem shape for convenience
    auto [M, N, K, L] = problem_shape_MNKL;

    // TMA requires special handling of strides to deal with coord codomain mapping
    // Represent the full tensors -- get these from TMA
    Tensor mA_mkl = params.tma_load_a.get_tma_tensor(make_shape(M,K,L));                          // (m,k,l)
    Tensor mB_nkl = params.tma_load_b.get_tma_tensor(make_shape(N,K,L));                          // (n,k,l)
    Tensor mSFA_mkl = params.tma_load_sfa.get_tma_tensor(shape(params.layout_SFA));
    Tensor mSFB_nkl = params.tma_load_sfb.get_tma_tensor(shape(params.layout_SFB));

    // Make tiled views, defer the slice
    Tensor gA_mkl = local_tile(mA_mkl, TileShape{}, make_coord(_,_,_), Step<_1, X,_1>{});        // (BLK_M,BLK_K,m,k,l)
    Tensor gB_nkl = local_tile(mB_nkl, TileShape{}, make_coord(_,_,_), Step< X,_1,_1>{});        // (BLK_N,BLK_K,n,k,l)

    Tensor gSFA_mkl = local_tile(mSFA_mkl, TileShape{}, make_coord(_,_,_), Step<_1, X,_1>{});    // (TILE_M,TILE_K,m,k,l)
    Tensor gSFB_nkl = local_tile(mSFB_nkl, TileShape{}, make_coord(_,_,_), Step< X,_1,_1>{});    // (TILE_N,TILE_K,n,k,l)

    return cute::make_tuple(gA_mkl, gB_nkl, gSFA_mkl, gSFB_nkl);
  }

  /// Perform a collective-scoped matrix multiply-accumulate
  /// Producer Perspective
  template <
    class TensorA, class TensorB,
    class TensorSFA, class TensorSFB,
    class KTileIterator, class BlockCoord
  >
  CUTLASS_DEVICE void
  load(
      Params const& params,
      MainloopPipeline pipeline,
      PipelineState smem_pipe_write,
      cute::tuple<TensorA, TensorB, TensorSFA, TensorSFB> const& load_inputs,
      BlockCoord const& blk_coord,
      KTileIterator k_tile_iter, int k_tile_count,
      int thread_idx,
      uint32_t block_rank_in_cluster,
      TensorStorage& shared_tensors) {
    int lane_predicate = cute::elect_one_sync();

    if (lane_predicate) {

      Tensor sA = make_tensor(make_smem_ptr(shared_tensors.smem_A.begin()), SmemLayoutA{});        // (BLK_M,BLK_K,PIPE)
      Tensor sB = make_tensor(make_smem_ptr(shared_tensors.smem_B.begin()), SmemLayoutB{});        // (BLK_N,BLK_K,PIPE)
      Tensor sSFA = make_tensor(make_smem_ptr(shared_tensors.smem_SFA.begin()), SmemLayoutSFA{});  // (BLK_M,BLK_K,PIPE)
      Tensor sSFB = make_tensor(make_smem_ptr(shared_tensors.smem_SFB.begin()), SmemLayoutSFB{});  // (BLK_N,BLK_K,PIPE)

      //
      // Prepare the TMA loads for A, B, SFA and SFB
      //

      auto [gA_mkl, gB_nkl, gSFA_mkl, gSFB_nkl] = load_inputs;

      auto block_tma_a = params.tma_load_a.get_slice(0);
      auto block_tma_b = params.tma_load_b.get_slice(0);

      auto block_tma_sfa = params.tma_load_sfa.get_slice(0);
      auto block_tma_sfb = params.tma_load_sfb.get_slice(0);

      // Partition the inputs based on the current block coordinates.
      auto [m_coord, n_coord, k_coord, l_coord] = blk_coord;

      auto broadcast_n = make_layout(
        make_shape(Int<size<1>(TileShapeSFB{}) / size<1>(TileShape{})>{},
                   Int<cute::numeric_limits<int>::max()>{}),
        make_stride(_0{}, size<1>(TileShapeSFB{}) / size<1>(TileShape{})));
      Tensor gA =   gA_mkl(_,_,m_coord,_,l_coord);                                                    // (BLK_M,BLK_K,k)
      Tensor gB =   gB_nkl(_,_,n_coord,_,l_coord);                                                    // (BLK_N,BLK_K,k)
      Tensor gSFA = gSFA_mkl(_,_,m_coord,_,l_coord);                                                  // (BLK_M,BLK_K,k)
      Tensor gSFB = gSFB_nkl(_,_,broadcast_n(n_coord),_,l_coord);                                     // (BLK_N,BLK_K,k)

      // Partition source and destination tensors for tma copies
      Tensor tAgA = block_tma_a.partition_S(gA);                                              // (TMA,TMA_M,TMA_K,k)
      Tensor tAsA = block_tma_a.partition_D(sA);                                              // (TMA,TMA_M,TMA_K,PIPE)

      Tensor tBgB = block_tma_b.partition_S(gB);                                              // (TMA,TMA_N,TMA_K,k)
      Tensor tBsB = block_tma_b.partition_D(sB);                                              // (TMA,TMA_N,TMA_K,PIPE)

      Tensor tAgSFA = block_tma_sfa.partition_S(gSFA);                                        // (TMA,TMA_M,TMA_K,k)
      Tensor tAsSFA = block_tma_sfa.partition_D(sSFA);                                        // (TMA,TMA_M,TMA_K,PIPE)

      Tensor tBgSFB = block_tma_sfb.partition_S(gSFB);                                        // (TMA,TMA_N,TMA_K,k)
      Tensor tBsSFB = block_tma_sfb.partition_D(sSFB);                                        // (TMA,TMA_N,TMA_K,PIPE)

      // Mainloop
      CUTLASS_PRAGMA_NO_UNROLL
      for ( ; k_tile_count > 0; --k_tile_count) {
        // LOCK smem_pipe_write for _writing_
        pipeline.producer_acquire(smem_pipe_write);

        //
        // Copy gmem to smem for *k_tile_iter
        //

        using BarrierType = typename MainloopPipeline::ProducerBarrierType;
        BarrierType* tma_barrier = pipeline.producer_get_barrier(smem_pipe_write);

        int write_stage = smem_pipe_write.index();
        copy(params.tma_load_a.with(*tma_barrier), tAgA(_,_,_,*k_tile_iter), tAsA(_,_,_,write_stage));
        copy(params.tma_load_b.with(*tma_barrier), tBgB(_,_,_,*k_tile_iter), tBsB(_,_,_,write_stage));

        copy(params.tma_load_sfa.with(*tma_barrier), tAgSFA(_,_,_,*k_tile_iter), tAsSFA(_,_,_,write_stage));
        copy(params.tma_load_sfb.with(*tma_barrier), tBgSFB(_,_,_,*k_tile_iter), tBsSFB(_,_,_,write_stage));

        // Advance k tile
        ++k_tile_iter;
        ++smem_pipe_write;
      }
    }
    __syncwarp();
  }

  /// Perform a Producer Epilogue to prevent early exit of blocks in a Cluster
  CUTLASS_DEVICE void
  load_tail(MainloopPipeline pipeline, PipelineState smem_pipe_write) {
    int lane_predicate = cute::elect_one_sync();

    // Issue the epilogue waits
    if (lane_predicate) {
      /* This helps avoid early exit of blocks in Cluster
       * Waits for all stages to either be released (all
       * Consumer UNLOCKs), or if the stage was never used
       * then would just be acquired since the phase was
       * still inverted from make_producer_start_state
       */
      pipeline.producer_tail(smem_pipe_write);
    }
  }

  /// Perform a collective-scoped matrix multiply-accumulate
  /// Consumer Perspective
  template <
    class FrgTensorC,
    class BlockCoord
  >
  CUTLASS_DEVICE void
  mma(MainloopPipeline pipeline,
      PipelineState smem_pipe_read,
      FrgTensorC& accum,
      int k_tile_count,
      int thread_idx,
      TensorStorage& shared_tensors,
      [[maybe_unused]] Params const& params,
      BlockCoord const& blk_coord) {
    using namespace cute;

    static_assert(is_rmem<FrgTensorC>::value, "C tensor must be rmem resident.");

    clear(accum);

    Tensor sA = make_tensor(make_smem_ptr(shared_tensors.smem_A.begin()), SmemLayoutA{});         // (BLK_M,BLK_K,PIPE)
    Tensor sB = make_tensor(make_smem_ptr(shared_tensors.smem_B.begin()), SmemLayoutB{});         // (BLK_N,BLK_K,PIPE)
    Tensor sSFA = make_tensor(make_smem_ptr(shared_tensors.smem_SFA.begin()), SmemLayoutSFA{});  // (BLK_M,BLK_K,PIPE)
    Tensor sSFB = [&]() {
      if constexpr (size<1>(TileShape{}) >= 128) {
        return make_tensor(make_smem_ptr(shared_tensors.smem_SFB.begin()), SmemLayoutSFB{});  // (BLK_N,BLK_K,PIPE)
      }
      else {
        Tensor temp = make_tensor(make_smem_ptr(shared_tensors.smem_SFB.begin()), SmemLayoutSFB{});  // (BLK_SFB_N,BLK_K,PIPE)
        auto n = get<1>(blk_coord);
        return temp(make_coord(_,n % (size<1>(TileShapeSFB{}) / size<1>(TileShape{}))), _, _);
      }
    }();

    //
    // Define C accumulators and A/B partitioning
    //

    TiledMma tiled_mma;
    auto thread_mma = tiled_mma.get_thread_slice(thread_idx);

    // Allocate fragments and descriptors
    Tensor tCrA = thread_mma.partition_fragment_A(sA(_,_,Int<0>{}));                         // (MMA,MMA_M,MMA_K)
    Tensor tCrB = thread_mma.partition_fragment_B(sB(_,_,Int<0>{}));                         // (MMA,MMA_N,MMA_K)

    Tensor tCrSFA = partition_fragment_SFA(sSFA(_,_,Int<0>{}), thread_mma);                  // (MMA,MMA_M,MMA_K)
    Tensor tCrSFB = partition_fragment_SFB(sSFB(_,_,Int<0>{}), thread_mma);                  // (MMA,MMA_N,MMA_K)

    //
    // Copy from smem to registers
    //

    // A
    auto smem_tiled_copy_A = make_tiled_copy_A(SmemCopyAtomA{}, tiled_mma);
    auto smem_thr_copy_A   = smem_tiled_copy_A.get_thread_slice(thread_idx);
    Tensor tCsA            = smem_thr_copy_A.partition_S(
      as_position_independent_swizzle_tensor(sA));                                      // (CPY,CPY_M,CPY_K,PIPE)
    Tensor tCrA_copy_view  = smem_thr_copy_A.retile_D(tCrA);                            //      (CPY,CPY_M,CPY_K)

    // B
    auto smem_tiled_copy_B = make_tiled_copy_B(SmemCopyAtomB{}, tiled_mma);
    auto smem_thr_copy_B   = smem_tiled_copy_B.get_thread_slice(thread_idx);
    Tensor tCsB            = smem_thr_copy_B.partition_S(
      as_position_independent_swizzle_tensor(sB));                                      // (CPY,CPY_M,CPY_K,PIPE)
    Tensor tCrB_copy_view  = smem_thr_copy_B.retile_D(tCrB);                            //      (CPY,CPY_M,CPY_K)

    // SFA
    auto tile_shape_mnk = tile_shape(tiled_mma);
    auto smem_tiled_copy_SFA = make_tiled_copy_impl(SmemCopyAtomSFA{},
                                                    get_layoutSFA_TV(tiled_mma),
                                                    make_shape(size<0>(tile_shape_mnk), size<2>(tile_shape_mnk))
                                                  );
    auto smem_thr_copy_SFA   = smem_tiled_copy_SFA.get_thread_slice(thread_idx);
    Tensor tCsSFA            = smem_thr_copy_SFA.partition_S(
        as_position_independent_swizzle_tensor(sSFA));                                      // (CPY,CPY_M,CPY_K,PIPE)
    Tensor tCrSFA_copy_view  = smem_thr_copy_SFA.retile_D(tCrSFA);                          //      (CPY,CPY_M,CPY_K)

    // SFB
    auto smem_tiled_copy_SFB = make_tiled_copy_impl(SmemCopyAtomSFB{},
                                                    get_layoutSFB_TV(tiled_mma),
                                                    make_shape(size<1>(tile_shape_mnk), size<2>(tile_shape_mnk))
                                                  );
    auto smem_thr_copy_SFB   = smem_tiled_copy_SFB.get_thread_slice(thread_idx);
    Tensor tCsSFB            = smem_thr_copy_SFB.partition_S(
      as_position_independent_swizzle_tensor(sSFB));                                       // (CPY,CPY_N,CPY_K,PIPE)
    Tensor tCrSFB_copy_view  = smem_thr_copy_SFB.retile_D(tCrSFB);                         //      (CPY,CPY_N,CPY_K)

    CUTE_STATIC_ASSERT_V(size<1>(tCsA) == size<1>(tCrA_copy_view));                        // CPY_M
    CUTE_STATIC_ASSERT_V(size<2>(tCsA) == size<2>(tCrA_copy_view));                        // CPY_K
    CUTE_STATIC_ASSERT_V(size<1>(tCrA) == size<1>(accum));                                 // MMA_M
    CUTE_STATIC_ASSERT_V(size<1>(tCrB) == size<2>(accum));                                 // MMA_N
    CUTE_STATIC_ASSERT_V(size<2>(tCsA) == size<2>(tCsB));                                  // CPY_K
    CUTE_STATIC_ASSERT_V(size<3>(tCsA) == size<3>(tCsB));                                  // PIPE
    CUTE_STATIC_ASSERT_V(Int<DispatchPolicy::Stages>{} == size<2>(sA));                    // PIPE
    CUTE_STATIC_ASSERT_V(Int<DispatchPolicy::Stages>{} == size<2>(sB));                    // PIPE

    CUTE_STATIC_ASSERT_V(size<1>(tCsSFA) == size<1>(tCrSFA_copy_view));                    // CPY_M
    CUTE_STATIC_ASSERT_V(size<2>(tCsSFA) == size<2>(tCrSFA_copy_view));                    // CPY_K
    CUTE_STATIC_ASSERT_V(size<1>(tCrSFA) == size<1>(accum));                               // MMA_M
    CUTE_STATIC_ASSERT_V(size<1>(tCrSFB) == size<2>(accum));                               // MMA_N
    CUTE_STATIC_ASSERT_V(size<2>(tCsSFA) == size<2>(tCsSFB));                              // CPY_K
    CUTE_STATIC_ASSERT_V(size<3>(tCsSFA) == size<3>(tCsSFB));                              // PIPE
    CUTE_STATIC_ASSERT_V(size<2>(sA) == size<2>(sSFA));                                    // PIPE
    CUTE_STATIC_ASSERT_V(size<2>(sB) == size<2>(sSFA));                                    // PIPE

    //
    // PIPELINED MAIN LOOP
    //

    // Size of the register pipeline
    auto K_BLOCK_MAX = size<2>(tCrA);

    int read_stage = smem_pipe_read.index();
    auto tCsA_stage   = tCsA(_,_,_,read_stage);
    auto tCsB_stage   = tCsB(_,_,_,read_stage);
    auto tCsSFA_stage = tCsSFA(_,_,_,read_stage);
    auto tCsSFB_stage = tCsSFB(_,_,_,read_stage);

    auto copy_kblock = [&](auto k_block) {
        // copy smem->rmem for A/B operand
      copy(smem_tiled_copy_A, tCsA_stage(_,_,k_block), tCrA_copy_view(_,_,k_block));
      copy(smem_tiled_copy_B, tCsB_stage(_,_,k_block), tCrB_copy_view(_,_,k_block));

      // Left shift A,B for FP4
      using MMAOp = typename TiledMma::MMA_Op;
      fp4_shift_A(MMAOp{}, tCrA_copy_view(_,_,k_block));
      fp4_shift_B(MMAOp{}, tCrB_copy_view(_,_,k_block));


      // Copy smem->rmem for SFA/SFB operand
      copy(tCsSFA_stage(_,_,k_block), tCrSFA_copy_view(_,_,k_block));
      copy(tCsSFB_stage(_,_,k_block), tCrSFB_copy_view(_,_,k_block));
    };

    // ---------------------------------------------------------------------------------------
    // MIXED-FORMAT DISPATCH
    // ---------------------------------------------------------------------------------------
    // The format choice does NOT live inside the MMA atom, where it would be natural. See
    // mma_sm120_mixed.hpp for the full measurement history; the short version is that a
    // predicated-off OMMA still consumes a tensor-pipe issue slot, this kernel is tensor-pipe
    // bound, and ptxas if-converts a format branch into `@P0 OMMA`/`@!P0 OMMA` pairs no matter
    // how it is written -- costing an exact 2x in issued tensor instructions.
    //
    // Nor does it live one level up, around a single cute::gemm. That was measured too: ptxas
    // if-converts the innermost diamond regardless of arm size (it predicated all 16 OMMAs one
    // way and all 16 the other with 16-OMMA arms, and still did so at 32 OMMAs per arm). Arm
    // size is not the lever.
    //
    // What ptxas will not if-convert is a region containing the pipeline's barriers and
    // shared-memory stage bookkeeping. So the dispatch wraps an entire k_tile iteration: each
    // arm is a full copy of the original loop body -- both k_blocks' smem->rmem copies, the
    // named barrier, the consumer release/acquire, and 32 OMMAs -- and the branch is paid once
    // per k_tile. This also keeps CUTLASS's register-level software pipeline (copy k_block+1
    // while multiplying k_block) exactly intact inside each arm, rather than flattening it.
    //
    // GRANULARITY THIS COSTS: the site is read once per k_tile from k_block 0's scale factors,
    // and applies to every MMA in that k_tile. Each warp evaluates it independently and the
    // barriers involved are arrival-counted by ID rather than by PC, so warps taking different
    // arms is safe. For the default Shape<_128,_128,_128> tile with its 4x2 warp arrangement the
    // granule the host-side tagging must respect is:
    //
    //     32 rows of A  x  64 columns of B  x  128 elements of K
    //
    // i.e. one warp's full MMA_M x MMA_N footprint, and both K64 halves of the k_tile.
    //
    // Tagging finer than that fails in two different ways, and the boundary between them is
    // worth knowing:
    //   - Finer than 32 rows / 64 columns but no finer than one atom (16 rows / 8 columns):
    //     every lane still agrees, because the flag is read from element 0, which lives in the
    //     first m-atom and first n-atom. The warp takes a single well-defined arm -- it just
    //     applies that atom's format to the rest of its footprint. Silently wrong numbers.
    //   - Finer than one atom: lanes of a warp read scale factors for different rows and
    //     disagree, so the warp splits across arms and mma.sync.aligned runs partially
    //     converged. That is undefined behaviour. Verified: an 8-row tagging trips the
    //     MIXFP4_DEBUG_UNIFORMITY check below with agreement mask 0x55555555 -- alternating
    //     lanes, exactly as SFALayout's ((2,2,8),64):((8,0,1),16) thread->row mapping predicts.
    using cute::SM120::BLOCKSCALED::SM120_16x8x64_TN_VS_MixedSite;

    // Atom counts this warp covers, and how they divide into independently-flagged granules.
    constexpr int kMmaM     = decltype(size<1>(tCrA))::value;                 // 2 for the default tile
    constexpr int kMmaN     = decltype(size<1>(tCrB))::value;                 // 8 for the default tile
    constexpr int kAAtoms   = MIXFP4_A_ATOMS_PER_GRANULE;
    constexpr int kBAtoms   = MIXFP4_B_ATOMS_PER_GRANULE;
    static_assert(kMmaM % kAAtoms == 0, "A granule must divide the warp's M atom count");
    static_assert(kMmaN % kBAtoms == 0, "B granule must divide the warp's N atom count");
    constexpr int kAGran    = kMmaM / kAAtoms;
    constexpr int kBGran    = kMmaN / kBAtoms;
#if defined(MIXFP4_JOINT_KB) && MIXFP4_JOINT_KB
    constexpr bool defined_joint_kb_for_a_all_e2m1 = true;
#else
    constexpr bool defined_joint_kb_for_a_all_e2m1 = false;
#endif
    (void) defined_joint_kb_for_a_all_e2m1;
#if defined(MIXFP4_JOINT_KA) && MIXFP4_JOINT_KA
    constexpr bool defined_joint_ka_for_b_all_e2m1 = true;
#else
    constexpr bool defined_joint_ka_for_b_all_e2m1 = false;
#endif
    (void) defined_joint_ka_for_b_all_e2m1;

    // -DMIXFP4_A_ALL_E2M1=1: A is E2M1 everywhere, so it contributes NO dispatch bits and the
    // whole budget goes to B. Leaving A's flag in the index and merely never setting it is not
    // enough -- the bit still doubles the arm count and deepens the branch tree, which measured
    // 1064.0 against 1055.6 for genuinely-mixed A, i.e. almost nothing. kADisp is the number of
    // bits A occupies in the dispatch INDEX; kAGran stays the blob's own A field width, since the
    // generated blob still encodes an (always-zero) A flag in its low bits.
// -DMIXFP4_B_ALL_E2M1=1 is the mirror: B is E2M1 everywhere and the budget goes to A. With the
// 8x1 arrangement a warp owns one m-atom, so A at its 16-row floor is 1 bit, 2 jointly for a
// 64-element K granule -- four arms.
#if defined(MIXFP4_B_ALL_E2M1) && MIXFP4_B_ALL_E2M1
    static_assert(defined_joint_ka_for_b_all_e2m1,
                  "MIXFP4_B_ALL_E2M1 currently requires -DMIXFP4_JOINT_KA=1");
    constexpr int kBDisp = 0;
#else
    constexpr int kBDisp = kBGran;
#endif
#if defined(MIXFP4_A_ALL_E2M1) && MIXFP4_A_ALL_E2M1
    // Only the joint-K-B path remaps the A-less index back into the blob's (A low, B above)
    // field layout. On the other paths the index would be fed to the blob verbatim and every arm
    // would be miscoded -- caught as unequal per-site OMMA counts ({0:96, 1:96, 2:32, 3:32}) by
    // the patcher, which is exactly what that invariant is for.
    constexpr int kADisp = 0;
#else
    constexpr int kADisp = kAGran;
#endif
    constexpr int kBitsPerKBlock = kADisp + kBDisp;

    // -DMIXFP4_JOINT_K=1: specialize the k_tile on *both* k_blocks' patterns at once, so the
    // format can change every 64 elements of K while the dispatch stays OUTSIDE the k_tile body.
    //
    // This is the lever that matters. Moving the dispatch inside the body costs ~97 cycles a time
    // (32x32x128 -> 32x32x64 is +3.3% -> +23.5% at identical granule, arms and OMMA count), and
    // that penalty is what a K granule of 64 normally buys you. Paying for K=64 in *arms* instead
    // -- 2^(2*bits) rather than 2^bits -- keeps the branch where it is cheap. The arm budget is
    // what limits it: with the blob path's cliff at 32 arms, 2 bits per k_block is the most that
    // fits, i.e. one A granule and one B granule.
#if defined(MIXFP4_JOINT_K) && MIXFP4_JOINT_K
    constexpr int kNumArms  = 1 << (2 * kBitsPerKBlock);
    static_assert(K_BLOCK_MAX == 2, "joint-K specialization assumes two k_blocks per k_tile");
    static_assert(kNumArms <= 32,
                  "joint-K needs 2^(2*bits) arms; past 32 cicc outlines the k_tile body and spills "
                  "the accumulators. Use a coarser granule.");
#elif defined(MIXFP4_JOINT_KB) && MIXFP4_JOINT_KB
    // Joint-K, but only for B. In a linear layer B is the weight operand, which is where fine K
    // granularity actually pays -- the quantizer groups weights in 16-element K blocks. A (the
    // activations) keeps a k_tile-wide K granule. Cost is kAGran + 2*kBGran bits instead of
    // 2*(kAGran + kBGran), which buys back a factor of 2^kAGran in arms.
    constexpr int kNumArms  = 1 << (kADisp + 2 * kBGran);
    static_assert(K_BLOCK_MAX == 2, "joint-K-B specialization assumes two k_blocks per k_tile");
    static_assert(kNumArms <= 32,
                  "joint-K-B needs 2^(kAGran + 2*kBGran) arms; past 32 cicc outlines the k_tile "
                  "body and spills the accumulators. Use a coarser granule.");
#elif defined(MIXFP4_JOINT_KA) && MIXFP4_JOINT_KA
    // Mirror of joint-K-B: A gets the 64-element K granule, B keeps the k_tile's 128. This is the
    // configuration that delivers a 16 row x 64 K format block -- one mma.sync's A footprint --
    // while leaving the branch outside the k_tile body where it costs cycles rather than stalls.
    constexpr int kNumArms  = 1 << (2 * kAGran + kBDisp);
    static_assert(K_BLOCK_MAX == 2, "joint-K-A specialization assumes two k_blocks per k_tile");
    // -DMIXFP4_ALLOW_OUTLINE=1 lifts the cap, which is what pricing the arm-count curve past 32
    // requires: 64 arms with a single per-k_tile dispatch is the cheapest branch placement there
    // is, so it bounds what any 6-bit granule can achieve however often it branches.
#if !(defined(MIXFP4_ALLOW_OUTLINE) && MIXFP4_ALLOW_OUTLINE)
    static_assert(kNumArms <= 32,
                  "joint-K-A needs 2^(2*kAGran + kBGran) arms; past 32 cicc outlines the k_tile "
                  "body and spills the accumulators. Use a coarser granule, or set "
                  "-DMIXFP4_ALLOW_OUTLINE=1 to measure it anyway.");
#endif
#else
    constexpr int kNumArms  = 1 << kBitsPerKBlock;
#endif

#if defined(MIXFP4_PTX) && MIXFP4_PTX
    // The generated PTX hardcodes the warp's atom counts, so a tile-shape change that the rest of
    // this file would absorb silently must fail loudly here instead.
    static_assert(kMmaM == MIXFP4_GEN_MMA_M, "generated PTX was built for a different MMA_M");
    static_assert(kMmaN == MIXFP4_GEN_MMA_N, "generated PTX was built for a different MMA_N");
#endif
#if defined(MIXFP4_BLOB) && MIXFP4_BLOB
    // Same hazard for the blob header: it hardcodes the warp's atom counts, so a CTA tile change
    // (MIXFP4_TILE_N) without regenerating would silently compute garbage.
    static_assert(kMmaM == MIXFP4_BLOBGEN_MMA_M, "blob header was built for a different MMA_M");
    static_assert(kMmaN == MIXFP4_BLOBGEN_MMA_N, "blob header was built for a different MMA_N");
#endif

    // Bit 7 of scale-factor byte 0 of each operand, for the k_block already resident in
    // registers. Every lane of a warp already holds the right value for the whole granule by
    // construction, so no shuffle/broadcast is needed.
    //
    // Defined before gemm_kblock because the PTX path calls it there, per k_block, purely for the
    // uniformity ballot -- that path's real dispatch lives inside the generated asm.
    auto read_site = [&](auto k_block) {
      auto sfa_words = recast<uint32_t>(tCrSFA(_,_,k_block));   // (1, MMA_M)
      auto sfb_words = recast<uint32_t>(tCrSFB(_,_,k_block));   // (1, MMA_N)

      // One bit per granule, read from that granule's first atom.
      uint32_t pattern = 0;
      // A occupies kADisp bits of the INDEX -- zero when it is pinned to E2M1 -- while the blob's
      // own A field keeps its kAGran width. gemm_kblock() converts between the two.
      for_each(make_int_sequence<kADisp>{}, [&](auto gi) {
        constexpr int g = decltype(gi)::value;
        if ((sfa_words(_0{}, C<g * kAAtoms>{}) & MIXFP4_FLAG_MASK) != 0) { pattern |= 1u << g; }
      });
      for_each(make_int_sequence<kBDisp>{}, [&](auto gi) {
        constexpr int g = decltype(gi)::value;
        if ((sfb_words(_0{}, C<g * kBAtoms>{}) & MIXFP4_FLAG_MASK) != 0) {
          pattern |= 1u << (kADisp + g);
        }
      });
      uint32_t const site = pattern;

      // Tagging finer than the granule above makes lanes of one warp disagree here, which sends
      // them down different arms and leaves mma.sync.aligned running partially converged -- that
      // is undefined behaviour, not merely wrong numbers, so it is worth catching loudly while
      // the host-side tagging is being written. Off by default; costs a ballot per dispatch.
#if defined(MIXFP4_DEBUG_UNIFORMITY) && MIXFP4_DEBUG_UNIFORMITY
      uint32_t const agree = __ballot_sync(0xffffffffu, site == __shfl_sync(0xffffffffu, site, 0));
      if (agree != 0xffffffffu) {
        printf("mixfp4: FATAL non-uniform format flag within a warp (thread %d, site %u, "
               "agreement mask 0x%08x) -- scale-factor tagging is finer than the dispatch "
               "granule\n", thread_idx, site, agree);
        __trap();
      }
#endif
      return site;
    };

#if (defined(MIXFP4_JOINT_K) && MIXFP4_JOINT_K) || (defined(MIXFP4_JOINT_KB) && MIXFP4_JOINT_KB) \
 || (defined(MIXFP4_JOINT_KA) && MIXFP4_JOINT_KA) \
 || (defined(MIXFP4_SPLIT_K) && MIXFP4_SPLIT_K)
    // Same flags as read_site(), but taken from SHARED memory rather than from the register
    // fragment.
    //
    // This is forced by the register-level software pipeline. At the top of a k_tile only
    // k_block 0's operands are resident -- k_block 1 is copied *inside* the body, by
    // copy_kblock(k_block_next). So read_site(_1{}) at dispatch time would read the previous
    // k_tile's registers, which is silently wrong (0.29 relative error, not 0.66: most granules
    // still happen to match). The smem stage, by contrast, holds the whole k_tile already --
    // the TMA producer filled it before consumer_wait released us.
    //
    // tCsSFA_stage(v, m, k_block) is what copy() feeds to tCrSFA_copy_view(v, m, k_block), so
    // element 0 of atom m is the same byte read_site() reads out of the recast register word.
    // Index the smem view LINEARLY, not by (v, atom).
    //
    // tCsSF*_stage is the copy *source* view, shaped (CPY, CPY_MN, CPY_K): CPY_MN is the copy
    // atom's tiling, which is not the MMA atom index -- for SFB the copy moves several atoms at a
    // time, so tCsSFB_stage(0, 4, k) is not atom 4. What copy() does guarantee is that logical
    // element i of the source lands in logical element i of tCr*_copy_view, which is a retile of
    // the register fragment and so shares its linear order. Atom a's byte 0 is therefore flat
    // index V*a, where V is the fragment's per-atom byte count.
    //
    // Getting this wrong is invisible whenever there is only one granule per operand (index 0 is
    // index 0 under any layout) and wrong by ~0.37 relative error as soon as there are two.
    constexpr int kSFAV = decltype(size<0>(tCrSFA))::value;
    constexpr int kSFBV = decltype(size<0>(tCrSFB))::value;
    auto read_a_smem = [&](auto k_block) {
      auto s = tCsSFA_stage(_,_,k_block);
      uint32_t bits = 0;
      for_each(make_int_sequence<kAGran>{}, [&](auto gi) {
        constexpr int g = decltype(gi)::value;
        if ((s(C<kSFAV * g * kAAtoms>{}).raw() & MIXFP4_FLAG_MASK) != 0) { bits |= 1u << g; }
      });
      return bits;
    };
    auto read_b_smem = [&](auto k_block) {
      auto s = tCsSFB_stage(_,_,k_block);
      uint32_t bits = 0;
      for_each(make_int_sequence<kBGran>{}, [&](auto gi) {
        constexpr int g = decltype(gi)::value;
        if ((s(C<kSFBV * g * kBAtoms>{}).raw() & MIXFP4_FLAG_MASK) != 0) { bits |= 1u << g; }
      });
      return bits;
    };
    // Only k_block 1's flags actually have to come from smem. k_block 0's operands ARE resident in
    // registers at dispatch time -- that is the whole premise of the register-level pipeline -- so
    // reading them back out of shared memory is a shared-memory round trip the kernel already paid
    // for. These two read the register fragment instead, which is what read_site() does.
    auto read_a_reg = [&](auto k_block) {
      auto sfa_words = recast<uint32_t>(tCrSFA(_,_,k_block));   // (1, MMA_M)
      uint32_t bits = 0;
      for_each(make_int_sequence<kAGran>{}, [&](auto gi) {
        constexpr int g = decltype(gi)::value;
        if ((sfa_words(_0{}, C<g * kAAtoms>{}) & MIXFP4_FLAG_MASK) != 0) { bits |= 1u << g; }
      });
      return bits;
    };
    auto read_b_reg = [&](auto k_block) {
      auto sfb_words = recast<uint32_t>(tCrSFB(_,_,k_block));   // (1, MMA_N)
      uint32_t bits = 0;
      for_each(make_int_sequence<kBGran>{}, [&](auto gi) {
        constexpr int g = decltype(gi)::value;
        if ((sfb_words(_0{}, C<g * kBAtoms>{}) & MIXFP4_FLAG_MASK) != 0) { bits |= 1u << g; }
      });
      return bits;
    };

    auto read_site_smem = [&](auto k_block) {
      uint32_t pattern = read_a_smem(k_block) | (read_b_smem(k_block) << kAGran);
      // Same guard as read_site(): tagging finer than the granule splits the warp across arms.
#if defined(MIXFP4_DEBUG_UNIFORMITY) && MIXFP4_DEBUG_UNIFORMITY
      uint32_t const agree =
          __ballot_sync(0xffffffffu, pattern == __shfl_sync(0xffffffffu, pattern, 0));
      if (agree != 0xffffffffu) {
        printf("mixfp4: FATAL non-uniform format flag within a warp (thread %d, site %u, "
               "agreement mask 0x%08x) -- scale-factor tagging is finer than the dispatch "
               "granule\n", thread_idx, pattern, agree);
        __trap();
      }
#endif
      return pattern;
    };
#endif

#if defined(MIXFP4_PIPE_IX) && MIXFP4_PIPE_IX
    // One jump index per k_block, kept in the same shape as the register pipeline it shadows:
    // slot k holds the index for k_block k, and it is filled by the copy_kblock(k) that loads that
    // k_block's operands -- one k_block ahead of the MMAs that consume it.
    static_assert(MIXFP4_PTX, "MIXFP4_PIPE_IX only applies to the generated-PTX dispatch");
    // k_block_next in the loop bodies is a plain int -- the ternary that wraps it collapses the
    // integral constant -- so the slot has to be named as a compile-time constant here instead.
    constexpr int kKBlocks = decltype(K_BLOCK_MAX)::value;
    uint32_t ix_pipe[kKBlocks][MIXFP4_GEN_GROUPS];
    auto fill_ix = [&](auto k_block_c) {
      constexpr int kSlot = decltype(k_block_c)::value;
      mixfp4::mma_index(recast<uint32_t>(tCrSFA(_,_,C<kSlot>{})),
                        recast<uint32_t>(tCrSFB(_,_,C<kSlot>{})),
                        ix_pipe[kSlot]);
    };
#endif

    // One k_block's worth of MMAs, with every atom's format fixed at compile time by `pattern`.
    //
    // This open-codes cute::gemm's dispatch [4] rather than calling it, because a single
    // cute::gemm applies one atom to all of its MMAs and the whole point here is to vary the
    // atom per sub-block. The traversal is deliberately identical to CuTe's row-major serpentine
    // (cute/algorithm/gemm.hpp), which exists to maximise operand register reuse between
    // consecutive MMAs -- reproducing it keeps the .reuse flags ptxas emits unchanged.
    auto gemm_kblock = [&](auto pattern_c, auto k_block) {
#if defined(MIXFP4_PTX) && MIXFP4_PTX
      // The generated asm does its own dispatch, so the C++ pattern is unused here.
      (void) pattern_c;
      // Tagging finer than the granule makes lanes of one warp disagree on the jump index, and
      // brx.idx.uni with a divergent index is undefined behaviour -- strictly worse than the C++
      // path's divergent `if`. This path bypasses the k_tile-level read_site(), so the ballot has
      // to happen here, per k_block, or it never runs at all.
#if defined(MIXFP4_DEBUG_UNIFORMITY) && MIXFP4_DEBUG_UNIFORMITY
      (void) read_site(k_block);
#endif
#if defined(MIXFP4_PIPE_IX) && MIXFP4_PIPE_IX
      // Index computed one k_block earlier (see the k_tile bodies below), so the branch reads a
      // register that has been resident for 16 MMAs.
      mixfp4::mma_kblock_ix(accum,
                            recast<uint32_t>(tCrA(_,_,k_block)),
                            recast<uint32_t>(tCrB(_,_,k_block)),
                            recast<uint32_t>(tCrSFA(_,_,k_block)),
                            recast<uint32_t>(tCrSFB(_,_,k_block)),
                            ix_pipe[decltype(k_block)::value]);
#else
      mixfp4::mma_kblock(accum,
                         recast<uint32_t>(tCrA(_,_,k_block)),
                         recast<uint32_t>(tCrB(_,_,k_block)),
                         recast<uint32_t>(tCrSFA(_,_,k_block)),
                         recast<uint32_t>(tCrSFB(_,_,k_block)));
#endif
#elif defined(MIXFP4_BLOB) && MIXFP4_BLOB
      // Same per-k_tile C++ dispatch as the default path, but this k_block's MMAs are one opaque
      // blob, which is what keeps cicc from outlining the body past 8 arms.
#if defined(MIXFP4_JOINT_K) && MIXFP4_JOINT_K
      // The arm encodes both k_blocks: k_block 0's flags in the low bits, k_block 1's above them.
      // Each k_block takes its own half, still entirely at compile time.
      constexpr uint32_t kMask  = (1u << kBitsPerKBlock) - 1;
      constexpr uint32_t kMine  =
          (decltype(pattern_c)::value >> (decltype(k_block)::value * kBitsPerKBlock)) & kMask;
      mixfp4::mma_kblock_blob<kMine>(
#elif defined(MIXFP4_JOINT_KB) && MIXFP4_JOINT_KB
      // Layout: A granule flags (shared by both k_blocks) in the low kAGran bits, then B's flags
      // for k_block 0, then B's for k_block 1. Reassemble into the blob's per-k_block convention,
      // which is A flags low, B flags above.
      constexpr uint32_t kJoint = decltype(pattern_c)::value;
      constexpr uint32_t kAbits = kJoint & ((1u << kADisp) - 1);
      constexpr uint32_t kBbits =
          (kJoint >> (kADisp + decltype(k_block)::value * kBGran)) & ((1u << kBGran) - 1);
      // kAGran, not kADisp: the blob's own A field keeps its width even when A is
      // absent from the dispatch index.
      constexpr uint32_t kMine  = kAbits | (kBbits << kAGran);
      mixfp4::mma_kblock_blob<kMine>(
#elif defined(MIXFP4_JOINT_KA) && MIXFP4_JOINT_KA
      // Layout: A's flags for k_block 0 in the low kAGran bits, A's for k_block 1 next, then B's
      // (shared by both k_blocks) on top. The blob wants A flags low, B flags above.
      constexpr uint32_t kJoint = decltype(pattern_c)::value;
      constexpr uint32_t kAbits =
          (kJoint >> (decltype(k_block)::value * kAGran)) & ((1u << kAGran) - 1);
      constexpr uint32_t kBbits = (kJoint >> (2 * kAGran)) & ((1u << kBDisp) - 1);
      constexpr uint32_t kMine  = kAbits | (kBbits << kAGran);
      mixfp4::mma_kblock_blob<kMine>(
#else
      constexpr uint32_t kIdxP_ = decltype(pattern_c)::value;
      constexpr uint32_t kAbP_  = kIdxP_ & ((1u << kADisp) - 1);
      constexpr uint32_t kBbP_  = (kIdxP_ >> kADisp) & ((1u << kBDisp) - 1);
      mixfp4::mma_kblock_blob<kAbP_ | (kBbP_ << kAGran)>(
#endif
          accum,
          recast<uint32_t>(tCrA(_,_,k_block)),
          recast<uint32_t>(tCrB(_,_,k_block)),
          recast<uint32_t>(tCrSFA(_,_,k_block)),
          recast<uint32_t>(tCrSFB(_,_,k_block)));
#else
      // Same remap as the joint paths: the dispatch index packs A into kADisp bits, the blob and
      // the per-atom site helpers expect kAGran. They differ whenever an operand is pinned.
      constexpr uint32_t kIdx_ = decltype(pattern_c)::value;
      constexpr uint32_t kAb_  = kIdx_ & ((1u << kADisp) - 1);
      constexpr uint32_t kBb_  = (kIdx_ >> kADisp) & ((1u << kBDisp) - 1);
      constexpr uint32_t kPattern = kAb_ | (kBb_ << kAGran);
      auto zipA = make_zip_tensor(tCrA(_,_,k_block), tCrSFA(_,_,k_block));
      auto zipB = make_zip_tensor(tCrB(_,_,k_block), tCrSFB(_,_,k_block));

      for_each(make_int_sequence<kMmaM>{}, [&](auto mi) {
        for_each(make_int_sequence<kMmaN>{}, [&](auto ni) {
          constexpr int m  = decltype(mi)::value;
          constexpr int n  = decltype(ni)::value;
          constexpr int ns = (m & 1) ? (kMmaN - 1 - n) : n;   // serpentine coordinate
          constexpr int site =
              int(mixfp4_detail::a_flag_of_atom<kAGran, kAAtoms>(kPattern, m)) |
              (int(mixfp4_detail::b_flag_of_atom<kAGran, kBAtoms>(kPattern, ns)) << 1);
          cute::gemm(MMA_Atom<SM120_16x8x64_TN_VS_MixedSite<site>>{},
                     accum(_,m,ns), zipA(_,m), zipB(_,ns), accum(_,m,ns));
        });
      });
#endif
    };

    // One k_tile of the main loop, specialized to a format site. Byte-for-byte the stock
    // mainloop body apart from gemm_kblock taking the site.
    auto k_tile_body = [&](auto site_c) {
      for_each(make_int_sequence<K_BLOCK_MAX>{}, [&] (auto k_block) {

        auto k_block_next = ((k_block + 1) == K_BLOCK_MAX) ? 0 : (k_block + 1);

        if (k_block == K_BLOCK_MAX - 1) {
          cutlass::arch::NamedBarrier::sync(
          thr_size(tiled_mma), cutlass::arch::ReservedNamedBarriers::Sm120MainloopBarrier);
          // UNLOCK smem_pipe_read, done _computing_ on it
          pipeline.consumer_release(smem_pipe_read);
          ++smem_pipe_read;
          read_stage = smem_pipe_read.index();
          tCsA_stage   = tCsA(_,_,_,read_stage);
          tCsB_stage   = tCsB(_,_,_,read_stage);
          tCsSFA_stage = tCsSFA(_,_,_,read_stage);
          tCsSFB_stage = tCsSFB(_,_,_,read_stage);
          pipeline.consumer_wait(smem_pipe_read);
        }

        copy_kblock(k_block_next);
#if defined(MIXFP4_PIPE_IX) && MIXFP4_PIPE_IX
        // consumed by the NEXT gemm_kblock, 16 MMAs from now
        fill_ix(C<(decltype(k_block)::value + 1) % kKBlocks>{});
#endif
        gemm_kblock(site_c, k_block);

      });
    };

    // The final k_tile, likewise.
    auto k_tile_tail_body = [&](auto site_c) {
      for_each(make_int_sequence<K_BLOCK_MAX>{}, [&] (auto k_block) {

        auto k_block_next = ((k_block + 1) == K_BLOCK_MAX) ? 0 : (k_block + 1);

        if (k_block == K_BLOCK_MAX - 1) {
          cutlass::arch::NamedBarrier::sync(
          thr_size(tiled_mma), cutlass::arch::ReservedNamedBarriers::Sm120MainloopBarrier);
          // UNLOCK smem_pipe_read, done _computing_ on it
          pipeline.consumer_release(smem_pipe_read);
          ++smem_pipe_read;
        }

        if (k_block_next > 0) {
          copy_kblock(k_block_next);
#if defined(MIXFP4_PIPE_IX) && MIXFP4_PIPE_IX
          fill_ix(C<(decltype(k_block)::value + 1) % kKBlocks>{});
#endif
        }
        gemm_kblock(site_c, k_block);

      });
    };

    // Run `body` under whichever of the four format sites this k_tile selected.
    //
    // Building with -DMIXFP4_NO_DISPATCH=1 removes the dispatch entirely and pins every k_tile to
    // site 0. That is not a functional mixed kernel -- it is the in-source performance ceiling,
    // structurally identical to stock nvfp4_gemm, so the cost of the dispatch can be read off as
    // a same-source A/B rather than against a separately-built binary.
    auto dispatch = [&](auto body) {
#if (defined(MIXFP4_NO_DISPATCH) && MIXFP4_NO_DISPATCH) || \
    (defined(MIXFP4_PTX) && MIXFP4_PTX)
      // PTX path: the dispatch lives inside the generated asm, so there is exactly one arm here.
      (void) &read_site;
      body(C<0>{});
#elif defined(MIXFP4_JOINT_K) && MIXFP4_JOINT_K
      // Both k_blocks' patterns in one index, so one branch outside the body covers a K granule
      // of 64. Reading k_block 1's flags here costs a second scale-factor read per k_tile, but
      // those registers are already resident and the reads are independent.
      mixfp4_detail::dispatch_pattern<0, kNumArms - 1>(
          read_site_smem(_0{}) | (read_site_smem(_1{}) << kBitsPerKBlock), body);
#elif defined(MIXFP4_JOINT_KB) && MIXFP4_JOINT_KB
      // A's flags once for the whole k_tile, B's once per k_block.
      // Only k_block 1's flags need the smem round trip; k_block 0's operands are resident in
      // registers at dispatch time. Reading them back from shared memory put an LDS on the
      // branch's critical path for nothing -- the same fix that was worth ~20 TFLOP/s on
      // joint-K-A.
      mixfp4_detail::dispatch_pattern<0, kNumArms - 1>(MIXFP4_IX(
          (kADisp ? read_a_reg(_0{}) : 0u) | (read_b_reg(_0{}) << kADisp)
                                           | (read_b_smem(_1{}) << (kADisp + kBGran)),
          kNumArms), body);
#elif defined(MIXFP4_JOINT_KA) && MIXFP4_JOINT_KA
      // A's flags once per k_block, B's once for the whole k_tile. Only k_block 1 needs the smem
      // read; the rest is already in the register fragment.
      mixfp4_detail::dispatch_pattern<0, kNumArms - 1>(
          read_a_reg(_0{}) | (read_a_smem(_1{}) << kAGran)
                           | ((kBDisp ? read_b_reg(_0{}) : 0u) << (2 * kAGran)), body);
#else
      mixfp4_detail::dispatch_pattern<0, kNumArms - 1>(MIXFP4_IX(read_site(_0{}), kNumArms), body);
#endif
    };

    pipeline.consumer_wait(smem_pipe_read);

    copy_kblock(_0{});
#if defined(MIXFP4_PIPE_IX) && MIXFP4_PIPE_IX
    fill_ix(_0{});   // seed the pipeline: k_block 0 of the first k_tile
#endif

#if defined(MIXFP4_SPLIT_K) && MIXFP4_SPLIT_K
    // ---------------------------------------------------------------------------------------
    // SPLIT-K: one dispatch per k_block, each arm carrying its own copies.
    // ---------------------------------------------------------------------------------------
    // The k_tile is cut at the pipeline barrier, which already sat between the two k_blocks, and
    // each half gets its own kBitsPerKBlock-wide dispatch. An arm is {copy the operands this half
    // will not need until the other half, then this half's 16 MMAs} -- i.e. exactly the region
    // ptxas needs to see whole in order to interleave LDSM with OMMA.
    //
    // Both patterns are read at the TOP of the k_tile, before the barrier. k_block 1's flags
    // belong to the stage being retired, so reading them after the restage would read the stage
    // the producer is about to refill.
    // If-conversion poison. Without it ptxas folds these arms into `@P OMMA`/`@!P OMMA` pairs --
    // measured: 128 of 448 OMMAs predicated, 683 TFLOP/s. A predicated-off OMMA still burns a
    // tensor-pipe issue slot, which is the 2x this whole design exists to avoid. One
    // `bar.warp.sync -1` per arm is something ptxas will not speculate across, and costs a single
    // WARPSYNC on an already-converged warp.
    auto no_ifconv = [] { asm volatile("bar.warp.sync -1;"); };

    // Pull the pipeline barrier and stage advance INSIDE the first arm, ahead of its MMAs.
    //
    // Splitting the k_tile into two separately-dispatched regions leaves the barrier stranded
    // between them, where nothing can cover it -- ncu shows the barrier stall going 0.69 -> 1.09
    // against the single-dispatch build. Inside the arm it overlaps this k_block's 16 MMAs, the
    // way it does in the whole-k_tile arm.
    //
    // Legal because consumer_release only guards shared-memory reads of the retiring stage, and
    // copy_kblock(1) just above is this stage's last one; the MMAs that follow touch registers.
    // MIXFP4_COPY_OUTSIDE hoists both smem->rmem copies out of the arms, holding arm count and
    // branch mechanism fixed. That isolates copy placement, which is the variable that decides
    // whether ptxas can interleave LDSM among the OMMAs (inside) or has to bunch them ahead of the
    // branch (outside) -- ncu puts mio_throttle at 0.05 inside versus 0.59 outside.
    auto kb0_region = [&](auto site_c) {
      no_ifconv();
#if !(defined(MIXFP4_COPY_OUTSIDE) && MIXFP4_COPY_OUTSIDE)
      copy_kblock(_1{});
#endif
#if defined(MIXFP4_EARLY_BARRIER) && MIXFP4_EARLY_BARRIER
      cutlass::arch::NamedBarrier::sync(
          thr_size(tiled_mma), cutlass::arch::ReservedNamedBarriers::Sm120MainloopBarrier);
      pipeline.consumer_release(smem_pipe_read);
      ++smem_pipe_read;
      read_stage    = smem_pipe_read.index();
      tCsA_stage    = tCsA(_,_,_,read_stage);
      tCsB_stage    = tCsB(_,_,_,read_stage);
      tCsSFA_stage  = tCsSFA(_,_,_,read_stage);
      tCsSFB_stage  = tCsSFB(_,_,_,read_stage);
      pipeline.consumer_wait(smem_pipe_read);
#endif
      gemm_kblock(site_c, _0{});
    };
    // Same, minus the wait: the last k_tile has no successor stage to wait on.
    auto kb0_region_tail = [&](auto site_c) {
      no_ifconv();
      copy_kblock(_1{});
#if defined(MIXFP4_EARLY_BARRIER) && MIXFP4_EARLY_BARRIER
      cutlass::arch::NamedBarrier::sync(
          thr_size(tiled_mma), cutlass::arch::ReservedNamedBarriers::Sm120MainloopBarrier);
      pipeline.consumer_release(smem_pipe_read);
      ++smem_pipe_read;
#endif
      gemm_kblock(site_c, _0{});
    };
    auto kb1_region = [&](auto site_c) {
      no_ifconv();
#if !(defined(MIXFP4_COPY_OUTSIDE) && MIXFP4_COPY_OUTSIDE)
      copy_kblock(_0{});
#endif
      gemm_kblock(site_c, _1{});
    };
    auto kb1_region_tail = [&](auto site_c) {
      no_ifconv();
      gemm_kblock(site_c, _1{});
    };

    CUTLASS_PRAGMA_NO_UNROLL
    for ( ; k_tile_count > 1; --k_tile_count) {
#if defined(MIXFP4_COPY_OUTSIDE) && MIXFP4_COPY_OUTSIDE
      copy_kblock(_1{});
#endif
      // Both flag reads come from the REGISTER fragment, not smem. k_block 0's operands are
      // resident on entry; k_block 1's are loaded by kb0_region's own copy_kblock(1), so by the
      // time the second dispatch runs they are in registers too. The earlier version of this path
      // read both from shared memory at the top of the k_tile, which is where its cost was: ncu
      // puts one dispatch at ~23 instructions, only ~6 of which are the branch tree.
      uint32_t const pat0 = read_site(_0{});

      mixfp4_detail::dispatch_pattern<0, kNumArms - 1>(pat0, kb0_region);

#if !(defined(MIXFP4_EARLY_BARRIER) && MIXFP4_EARLY_BARRIER)
      cutlass::arch::NamedBarrier::sync(
          thr_size(tiled_mma), cutlass::arch::ReservedNamedBarriers::Sm120MainloopBarrier);
      pipeline.consumer_release(smem_pipe_read);
      ++smem_pipe_read;
      read_stage    = smem_pipe_read.index();
      tCsA_stage    = tCsA(_,_,_,read_stage);
      tCsB_stage    = tCsB(_,_,_,read_stage);
      tCsSFA_stage  = tCsSFA(_,_,_,read_stage);
      tCsSFB_stage  = tCsSFB(_,_,_,read_stage);
      pipeline.consumer_wait(smem_pipe_read);
#endif

#if defined(MIXFP4_COPY_OUTSIDE) && MIXFP4_COPY_OUTSIDE
      copy_kblock(_0{});
#endif
      mixfp4_detail::dispatch_pattern<0, kNumArms - 1>(read_site(_1{}), kb1_region);
    } // k_tile_count

    // Hoist out the last k_tile: no stage follows it, so neither the wait nor k_block 0's copy
    // happens.
    {
      // The tail must hoist the copy too, or the last k_tile never loads k_block 1 -- 0.39
      // relative error, and only in the final k_tile, which is exactly how it presents.
#if defined(MIXFP4_COPY_OUTSIDE) && MIXFP4_COPY_OUTSIDE
      copy_kblock(_1{});
#endif
#if defined(MIXFP4_EARLY_BARRIER) && MIXFP4_EARLY_BARRIER
      mixfp4_detail::dispatch_pattern<0, kNumArms - 1>(read_site(_0{}), kb0_region_tail);
#else
      mixfp4_detail::dispatch_pattern<0, kNumArms - 1>(read_site(_0{}), kb0_region);

      cutlass::arch::NamedBarrier::sync(
          thr_size(tiled_mma), cutlass::arch::ReservedNamedBarriers::Sm120MainloopBarrier);
      pipeline.consumer_release(smem_pipe_read);
      ++smem_pipe_read;
#endif

      mixfp4_detail::dispatch_pattern<0, kNumArms - 1>(read_site(_1{}), kb1_region_tail);
    }
#elif ((defined(MIXFP4_JOINT_KA) && MIXFP4_JOINT_KA) || \
       (defined(MIXFP4_JOINT_KB) && MIXFP4_JOINT_KB)) && \
      defined(MIXFP4_PIPE_FLAGS) && MIXFP4_PIPE_FLAGS
    // ---------------------------------------------------------------------------------------
    // Software-pipeline the dispatch index itself.
    // ---------------------------------------------------------------------------------------
    // Joint-K-A needs one flag that is NOT in registers -- k_block 1's, which has to come from the
    // smem stage. Read at the top of the k_tile, that LDS sits directly on the critical path into
    // the branch tree, and nothing overlaps it.
    //
    // But the operands for the NEXT k_tile become available partway through this one: right after
    // copy_kblock(0) reloads the register fragment from the freshly waited-on stage. Computing the
    // next arm index there gives the load this k_block's 16 MMAs to complete behind, and leaves
    // the branch with a value already in a register.
    auto next_pattern = [&] {
#if defined(MIXFP4_JOINT_KA) && MIXFP4_JOINT_KA
      return read_a_reg(_0{}) | (read_a_smem(_1{}) << kAGran)
                              | ((kBDisp ? read_b_reg(_0{}) : 0u) << (2 * kAGran));
#else   // joint-K-B: A once per k_tile (or absent), B once per k_block
      return (kADisp ? read_a_reg(_0{}) : 0u) | (read_b_reg(_0{}) << kADisp)
                                              | (read_b_smem(_1{}) << (kADisp + kBGran));
#endif
    };

    uint32_t pattern_cur  = next_pattern();
    uint32_t pattern_next = 0;

    auto k_tile_body_pipe = [&](auto site_c) {
      for_each(make_int_sequence<K_BLOCK_MAX>{}, [&] (auto k_block) {
        auto k_block_next = ((k_block + 1) == K_BLOCK_MAX) ? 0 : (k_block + 1);

        if (k_block == K_BLOCK_MAX - 1) {
          cutlass::arch::NamedBarrier::sync(
            thr_size(tiled_mma), cutlass::arch::ReservedNamedBarriers::Sm120MainloopBarrier);
          pipeline.consumer_release(smem_pipe_read);
          ++smem_pipe_read;
          read_stage   = smem_pipe_read.index();
          tCsA_stage   = tCsA(_,_,_,read_stage);
          tCsB_stage   = tCsB(_,_,_,read_stage);
          tCsSFA_stage = tCsSFA(_,_,_,read_stage);
          tCsSFB_stage = tCsSFB(_,_,_,read_stage);
          pipeline.consumer_wait(smem_pipe_read);
        }

        copy_kblock(k_block_next);

        if (k_block == K_BLOCK_MAX - 1) {
          // The stage just waited on is the next k_tile's, and copy_kblock(0) has just refilled
          // the register fragment from it, so every flag the next arm needs is readable now.
          pattern_next = next_pattern();
        }

        gemm_kblock(site_c, k_block);
      });
    };

    CUTLASS_PRAGMA_NO_UNROLL
    for ( ; k_tile_count > 1; --k_tile_count) {
      mixfp4_detail::dispatch_pattern<0, kNumArms - 1>(pattern_cur, k_tile_body_pipe);
      pattern_cur = pattern_next;
    } // k_tile_count

    // The last body already computed the tail's arm.
    mixfp4_detail::dispatch_pattern<0, kNumArms - 1>(pattern_cur, k_tile_tail_body);
#elif defined(MIXFP4_DISPATCH_PER_CTA) && MIXFP4_DISPATCH_PER_CTA
    // ---------------------------------------------------------------------------------------
    // ONE dispatch for the whole CTA: the entire k-loop lives inside each arm.
    // ---------------------------------------------------------------------------------------
    // Correct only when the format is K-INVARIANT -- the flags are read once, before the loop, and
    // applied to every k_tile. That is exactly what a per-channel format choice, or any sorted
    // layout, produces (MIXFP4_TAG=rowcol models it).
    //
    // The payoff is that both costs vanish at once. There is no branch in the k-loop, so nothing
    // interrupts the OMMA stream; and although the binary still holds every arm, a CTA executes
    // ONE of them for its entire life, so the instruction-cache working set is a single k_tile
    // body rather than the whole jump table. MIXFP4_TAG=rowcol already showed that second effect
    // is worth +74 TFLOP/s on its own at 64 arms.
    mixfp4_detail::dispatch_pattern<0, kNumArms - 1>(read_site(_0{}), [&](auto site_c) {
      CUTLASS_PRAGMA_NO_UNROLL
      for ( ; k_tile_count > 1; --k_tile_count) {
        k_tile_body(site_c);
      }
      k_tile_tail_body(site_c);
    });
#else
    CUTLASS_PRAGMA_NO_UNROLL
    for ( ; k_tile_count > 1; --k_tile_count) {
      //
      // Compute on k_tile
      //
      dispatch(k_tile_body);
    } // k_tile_count

    //
    // Hoist out last k_tile
    //
    dispatch(k_tile_tail_body);
#endif
}

  /// Perform a Consumer Epilogue to release all buffers
  CUTLASS_DEVICE void
  mma_tail(MainloopPipeline, PipelineState, int) {
  }
};

/////////////////////////////////////////////////////////////////////////////////////////////////

} // namespace cutlass::gemm::collective

/////////////////////////////////////////////////////////////////////////////////////////////////
