// Hand-written raw-CuTe NVFP4 (e2m1, block-scaled) GEMM for GeForce Blackwell (sm_120),
// D = alpha * A * B + beta * C.
//
// Unlike src/nvfp4_gemm.cu (which builds the kernel through CUTLASS's CollectiveBuilder),
// this file writes the TMA loads, the mainloop pipeline, the block-scaled MMA call, the
// producer/consumer warp-specialized kernel, and the epilogue ourselves -- using CuTe's
// layout/copy/mma primitives directly. Two categories of code are still reused verbatim
// from CUTLASS rather than hand-derived:
//   1. Pre-built hardware-wrapper library primitives with no connection to layout control
//      (cutlass::PipelineTmaAsync for mbarrier-based double buffering; cute::make_tma_copy;
//      the MMA_Traits<SM120::BLOCKSCALED::...> atom itself).
//   2. Type-level-only layout computations pulled from cutlass::gemm::collective::CollectiveBuilder
//      (SmemLayoutAtom[A,B,SFA,SFB], SmemCopyAtom[A,B], TiledMma, PipelineStages) -- these
//      encode intricate swizzle/stage-count arithmetic that CUTLASS engineers derived and
//      verified; referencing the types is like using cutlass::layout::RowMajor rather than
//      hand-deriving row-major stride arithmetic. No device code is generated by this --
//      CollectiveBuilder<...>::TiledMma etc. are just type aliases.
// The persistent tile scheduler uses a simple global-atomic-counter loop rather than
// CUTLASS's hardware Cluster-Launch-Control-based PersistentTileSchedulerSm100 -- that
// class wraps raw `clusterlaunchcontrol.*` PTX instructions, which has nothing to do with
// CuTe layout control and would add hardware-wrapper-transcription risk for no benefit.
// The epilogue is a simple direct-to-global store (no TMA store, no smem staging).

#include <cstdlib>
#include <iostream>

#include "cute/tensor.hpp"
#include "cute/arch/mma_sm120.hpp"
#include "cute/atom/mma_traits_sm120.hpp"

#include "cutlass/cutlass.h"
#include "cutlass/arch/barrier.h"
#include "cutlass/detail/sm100_blockscaled_layout.hpp"
#include "cutlass/gemm/collective/collective_builder.hpp"
#include "cutlass/kernel_hardware_info.hpp"
#include "cutlass/numeric_types.h"
#include "cutlass/pipeline/pipeline.hpp"
#include "cutlass/util/device_memory.h"
#include "cutlass/util/host_tensor.h"
#include "cutlass/util/packed_stride.hpp"
#include "cutlass/util/reference/host/gett.hpp"
#include "cutlass/util/reference/host/tensor_compare.h"
#include "cutlass/util/reference/host/tensor_fill.h"
#include "cutlass/util/reference/host/tensor_norm.h"

#include "helper.h"

using namespace cute;

//
// Problem configuration
//

using ElementA = cutlass::float_e2m1_t;
using ElementB = cutlass::float_e2m1_t;
using ElementSF = cutlass::float_ue4m3_t;  // NVFP4 block size is 16 (baked into nv_float4_t below)

using LayoutATag = cutlass::layout::RowMajor;
using LayoutBTag = cutlass::layout::ColumnMajor;
using LayoutCTag = cutlass::layout::RowMajor;
using LayoutDTag = cutlass::layout::RowMajor;
constexpr int AlignmentA = 32;
constexpr int AlignmentB = 32;

using ElementC = cutlass::bfloat16_t;
using ElementD = cutlass::bfloat16_t;
using ElementAccumulator = float;
using ElementCompute = float;

using TileShape = Shape<_128, _128, _128>;
using TileShapeMN = Shape<_128, _128>;
using ClusterShape = Shape<_1, _1, _1>;

//
// Pull already-verified layout/atom types from CollectiveBuilder (type-level only --
// this does not instantiate CUTLASS's own mainloop/kernel, just computes types).
//

// NOTE: the CollectiveBuilder's public ElementPairA/B must be the wrapped nv_float4_t<...>
// type (matching src/nvfp4_gemm.cu), NOT a raw cute::tuple<Element,SF> -- the latter also
// compiles (there's a blockscaled_type<..., cute::tuple<T,SF>> specialization) but computes
// SfVectorSize via a different, schedule-tag-driven path instead of nv_float4_t's fixed 16,
// which silently selected the wrong scale-factor vector size and corrupted the derived
// layouts / TMA descriptors.
using MainloopBuilder = cutlass::gemm::collective::CollectiveBuilder<
    cutlass::arch::Sm120, cutlass::arch::OpClassBlockScaledTensorOp,
    cutlass::nv_float4_t<ElementA>, LayoutATag, AlignmentA,
    cutlass::nv_float4_t<ElementB>, LayoutBTag, AlignmentB,
    ElementAccumulator, TileShape, ClusterShape,
    cutlass::gemm::collective::StageCountAutoCarveout<0>,  // no epilogue smem to carve out
    cutlass::gemm::collective::KernelScheduleAuto>;

using TiledMma = typename MainloopBuilder::TiledMma;
using Sm1xxBlkScaledConfig = typename MainloopBuilder::Sm1xxBlkScaledConfig;
constexpr int PipelineStages = MainloopBuilder::PipelineStages;

using SmemLayoutAtomA = typename MainloopBuilder::SmemLayoutAtomA;
using SmemLayoutAtomB = typename MainloopBuilder::SmemLayoutAtomB;
using SmemLayoutAtomSFA = typename MainloopBuilder::SmemLayoutAtomSFA;
using SmemLayoutAtomSFB = typename MainloopBuilder::SmemLayoutAtomSFB;
using SmemCopyAtomA = typename MainloopBuilder::SmemCopyAtomA;
using SmemCopyAtomB = typename MainloopBuilder::SmemCopyAtomB;
using SmemCopyAtomSFA = typename MainloopBuilder::SmemCopyAtomSFA;
using SmemCopyAtomSFB = typename MainloopBuilder::SmemCopyAtomSFB;
using GmemTiledCopyA = typename MainloopBuilder::GmemTiledCopyA;
using GmemTiledCopyB = typename MainloopBuilder::GmemTiledCopyB;
using GmemTiledCopySFA = typename MainloopBuilder::GmemTiledCopySFA;
using GmemTiledCopySFB = typename MainloopBuilder::GmemTiledCopySFB;

using StrideA = cutlass::gemm::TagToStrideA_t<LayoutATag>;
using StrideB = cutlass::gemm::TagToStrideB_t<LayoutBTag>;
using StrideC = cutlass::gemm::TagToStrideC_t<LayoutCTag>;
using StrideD = cutlass::gemm::TagToStrideC_t<LayoutDTag>;
using LayoutSFA = decltype(Sm1xxBlkScaledConfig::deduce_layoutSFA());
using LayoutSFB = decltype(Sm1xxBlkScaledConfig::deduce_layoutSFB());

// Full multi-stage smem layouts -- same construction CUTLASS's own sm120 blockscaled
// mainloop uses (include/cutlass/gemm/collective/sm120_blockscaled_mma_tma.hpp:185-215).
using SmemLayoutA = decltype(tile_to_shape(
    SmemLayoutAtomA{},
    make_shape(shape<0>(TileShape{}), shape<2>(TileShape{}), Int<PipelineStages>{}),
    conditional_t<cutlass::gemm::detail::is_major<0, StrideA>(), Step<_2, _1, _3>, Step<_1, _2, _3>>{}));
using SmemLayoutB = decltype(tile_to_shape(
    SmemLayoutAtomB{},
    make_shape(shape<1>(TileShape{}), shape<2>(TileShape{}), Int<PipelineStages>{}),
    conditional_t<cutlass::gemm::detail::is_major<0, StrideB>(), Step<_2, _1, _3>, Step<_1, _2, _3>>{}));

using SmemLayoutSFA = decltype(make_layout(
    append(shape(SmemLayoutAtomSFA{}), Int<PipelineStages>{}),
    append(stride(SmemLayoutAtomSFA{}), size(filter_zeros(SmemLayoutAtomSFA{})))));
using SmemLayoutSFB = decltype(make_layout(
    append(shape(SmemLayoutAtomSFB{}), Int<PipelineStages>{}),
    append(stride(SmemLayoutAtomSFB{}), size(filter_zeros(SmemLayoutAtomSFB{})))));
// (TileShape N == 128 here, so the "<128 broadcast" special case CUTLASS's mainloop
// handles for narrow-N tiles never triggers -- SmemLayoutSFB above is already final.)

static_assert(size<1>(TileShape{}) >= 128, "This file assumes TileShape N >= 128 (see SFB broadcast note above).");

constexpr bool IsF8F6F4 = false;  // size<2>(TiledMma::Shape_MNK) == 64 here, not 32; see cutlass/detail/collective.hpp is_sm120_f8f6f4().
using SmemAllocTypeA = cute::conditional_t<IsF8F6F4, uint8_t, typename TiledMma::ValTypeA>;
using SmemAllocTypeB = cute::conditional_t<IsF8F6F4, uint8_t, typename TiledMma::ValTypeB>;
// Since IsF8F6F4 is false here, these are just ElementA/ElementB; kept as named types (matching
// CUTLASS's own mainloop) since make_tma_copy needs a recast_ptr<TmaInternalElement...> cast below.
using TmaInternalElementA = ElementA;
using TmaInternalElementB = ElementB;

static constexpr uint32_t TmaTransactionBytesMK = static_cast<uint32_t>(
    cutlass::bits_to_bytes(cosize(take<0, 2>(SmemLayoutSFA{})) * cute::sizeof_bits_v<ElementSF>) +
    cutlass::bits_to_bytes(size(take<0, 2>(SmemLayoutA{})) * sizeof_bits<ElementA>::value));
static constexpr uint32_t TmaTransactionBytesNK = static_cast<uint32_t>(
    cutlass::bits_to_bytes(cosize(take<0, 2>(SmemLayoutSFB{})) * cute::sizeof_bits_v<ElementSF>) +
    cutlass::bits_to_bytes(size(take<0, 2>(SmemLayoutB{})) * sizeof_bits<ElementB>::value));
static constexpr uint32_t TmaTransactionBytes = TmaTransactionBytesMK + TmaTransactionBytesNK;

//
// Shared memory
//

using MainloopPipeline = cutlass::PipelineTmaAsync<PipelineStages>;
using PipelineState = cutlass::PipelineState<PipelineStages>;

struct SharedStorage {
  struct TensorStorage : cute::aligned_struct<128, _0> {
    alignas(1024) cute::ArrayEngine<SmemAllocTypeA, cute::cosize_v<SmemLayoutA>> smem_A;
    alignas(1024) cute::ArrayEngine<SmemAllocTypeB, cute::cosize_v<SmemLayoutB>> smem_B;
    alignas(16) cute::ArrayEngine<ElementSF, cute::cosize_v<SmemLayoutSFA>> smem_SFA;
    alignas(16) cute::ArrayEngine<ElementSF, cute::cosize_v<SmemLayoutSFB>> smem_SFB;
  } tensors;
  alignas(16) typename MainloopPipeline::SharedStorage pipeline_storage;
};

//
// Adhoc SFA/SFB fragment partitioning helpers -- CUTLASS's own comment calls this
// "Temporary adhoc partitioning for scaling factors" (not general TiledMma API,
// duplicated near-verbatim from sm120_blockscaled_mma_tma.hpp:429-566).
//

template <class SFATensor, class Atom, class TiledThr, class TiledPerm>
CUTE_HOST_DEVICE constexpr auto thrfrg_SFA(SFATensor&& sfatensor, TiledMMA<Atom, TiledThr, TiledPerm>& mma) {
  using AtomShape_MNK = typename Atom::Shape_MNK;
  using AtomLayoutSFA_TV = typename Atom::Traits::SFALayout;

  auto permutation_mnk = TiledPerm{};
  auto thr_layout_vmnk = mma.get_thr_layout_vmnk();

  auto t_tile = make_tile(get<0>(permutation_mnk), get<2>(permutation_mnk));
  auto t_tensor = logical_divide(sfatensor, t_tile);

  auto a_tile = make_tile(make_layout(size<0>(AtomShape_MNK{})), make_layout(size<2>(AtomShape_MNK{})));
  auto a_tensor = zipped_divide(t_tensor, a_tile);

  auto tv_tensor = a_tensor.compose(AtomLayoutSFA_TV{}, _);

  auto thr_tile = make_tile(_, make_tile(make_layout(size<1>(thr_layout_vmnk)), make_layout(size<3>(thr_layout_vmnk))));
  return zipped_divide(tv_tensor, thr_tile);
}

template <class SFBTensor, class Atom, class TiledThr, class TiledPerm>
CUTE_HOST_DEVICE constexpr auto thrfrg_SFB(SFBTensor&& sfbtensor, TiledMMA<Atom, TiledThr, TiledPerm>& mma) {
  using AtomShape_MNK = typename Atom::Shape_MNK;
  using AtomLayoutSFB_TV = typename Atom::Traits::SFBLayout;

  auto permutation_mnk = TiledPerm{};
  auto thr_layout_vmnk = mma.get_thr_layout_vmnk();

  auto t_tile = make_tile(get<1>(permutation_mnk), get<2>(permutation_mnk));
  auto t_tensor = logical_divide(sfbtensor, t_tile);

  auto a_tile = make_tile(make_layout(size<1>(AtomShape_MNK{})), make_layout(size<2>(AtomShape_MNK{})));
  auto a_tensor = zipped_divide(t_tensor, a_tile);

  auto tv_tensor = a_tensor.compose(AtomLayoutSFB_TV{}, _);

  auto thr_tile = make_tile(_, make_tile(make_layout(size<2>(thr_layout_vmnk)), make_layout(size<3>(thr_layout_vmnk))));
  return zipped_divide(tv_tensor, thr_tile);
}

template <class SFATensor, class ThrMma>
CUTE_HOST_DEVICE constexpr auto partition_fragment_SFA(SFATensor&& sfatensor, ThrMma& thread_mma) {
  using ValTypeSF = typename ThrMma::Atom::Traits::ValTypeSF;
  auto thr_tensor = make_tensor(static_cast<SFATensor&&>(sfatensor).data(), thrfrg_SFA(sfatensor.layout(), thread_mma));
  auto thr_vmnk = thread_mma.thr_vmnk_;
  auto thr_vmk = make_coord(get<0>(thr_vmnk), make_coord(get<1>(thr_vmnk), get<3>(thr_vmnk)));
  auto partition_SFA = thr_tensor(thr_vmk, make_coord(_, repeat<rank<1, 1>(thr_tensor)>(_)));
  return make_fragment_like<ValTypeSF>(partition_SFA);
}

template <class SFBTensor, class ThrMma>
CUTE_HOST_DEVICE constexpr auto partition_fragment_SFB(SFBTensor&& sfbtensor, ThrMma& thread_mma) {
  using ValTypeSF = typename ThrMma::Atom::Traits::ValTypeSF;
  auto thr_tensor = make_tensor(static_cast<SFBTensor&&>(sfbtensor).data(), thrfrg_SFB(sfbtensor.layout(), thread_mma));
  auto thr_vmnk = thread_mma.thr_vmnk_;
  auto thr_vnk = make_coord(get<0>(thr_vmnk), make_coord(get<2>(thr_vmnk), get<3>(thr_vmnk)));
  auto partition_SFB = thr_tensor(thr_vnk, make_coord(_, repeat<rank<1, 1>(thr_tensor)>(_)));
  return make_fragment_like<ValTypeSF>(partition_SFB);
}

template <class TiledMmaT>
CUTE_HOST_DEVICE constexpr auto get_layoutSFA_TV(TiledMmaT& mma) {
  auto tile_shape_mnk = tile_shape(mma);
  auto ref_A = make_layout(make_shape(size<0>(tile_shape_mnk), size<2>(tile_shape_mnk)));
  auto thr_layout_vmnk = mma.get_thr_layout_vmnk();

  auto atile = make_tile(_, make_tile(make_layout(make_shape(size<1>(thr_layout_vmnk), size<2>(thr_layout_vmnk)),
                                                   make_stride(Int<1>{}, Int<0>{})),
                                       _));

  auto thridx_2_thrid = right_inverse(thr_layout_vmnk);
  return thrfrg_SFA(ref_A, mma).compose(atile, _).compose(thridx_2_thrid, _);
}

template <class TiledMmaT>
CUTE_HOST_DEVICE constexpr auto get_layoutSFB_TV(TiledMmaT& mma) {
  auto tile_shape_mnk = tile_shape(mma);
  auto ref_B = make_layout(make_shape(size<1>(tile_shape_mnk), size<2>(tile_shape_mnk)));
  auto thr_layout_vmnk = mma.get_thr_layout_vmnk();

  auto btile = make_tile(_, make_tile(make_layout(make_shape(size<1>(thr_layout_vmnk), size<2>(thr_layout_vmnk)),
                                                   make_stride(Int<0>{}, Int<1>{})),
                                       _));

  auto thridx_2_thrid = right_inverse(thr_layout_vmnk);
  return thrfrg_SFB(ref_B, mma).compose(btile, _).compose(thridx_2_thrid, _);
}

//
// Host-side TMA descriptors (built once, passed to the kernel by value)
//

struct Params {
  using TMA_A = decltype(make_tma_copy(
      GmemTiledCopyA{}, make_tensor(recast_ptr<TmaInternalElementA>(nullptr), repeat_like(StrideA{}, int32_t(0)), StrideA{}),
      SmemLayoutA{}(_, _, Int<0>{}), make_shape(shape<0>(TileShape{}), shape<2>(TileShape{})), _1{}));
  using TMA_B = decltype(make_tma_copy(
      GmemTiledCopyB{}, make_tensor(recast_ptr<TmaInternalElementB>(nullptr), repeat_like(StrideB{}, int32_t(0)), StrideB{}),
      SmemLayoutB{}(_, _, Int<0>{}), make_shape(shape<1>(TileShape{}), shape<2>(TileShape{})), _1{}));
  using TMA_SFA = decltype(make_tma_copy<uint16_t>(
      GmemTiledCopySFA{}, make_tensor(static_cast<ElementSF const*>(nullptr), LayoutSFA{}),
      SmemLayoutSFA{}(_, _, Int<0>{}), make_shape(shape<0>(TileShape{}), shape<2>(TileShape{})), _1{}));
  using TMA_SFB = decltype(make_tma_copy<uint16_t>(
      GmemTiledCopySFB{}, make_tensor(static_cast<ElementSF const*>(nullptr), LayoutSFB{}),
      SmemLayoutSFB{}(_, _, Int<0>{}), make_shape(shape<1>(TileShape{}), shape<2>(TileShape{})), _1{}));

  TMA_A tma_a;
  TMA_B tma_b;
  TMA_SFA tma_sfa;
  TMA_SFB tma_sfb;
  LayoutSFA layout_SFA;
  LayoutSFB layout_SFB;

  ElementC const* ptr_C;
  StrideC dC;
  ElementD* ptr_D;
  StrideD dD;

  int M, N, K, L;
  float alpha, beta;
  int* tile_counter;
};

Params make_params(int M, int N, int K, int L, ElementA const* ptr_A, ElementB const* ptr_B, ElementSF const* ptr_SFA,
                    ElementSF const* ptr_SFB, ElementC const* ptr_C, ElementD* ptr_D, float alpha, float beta,
                    int* tile_counter) {
  StrideA dA = cutlass::make_cute_packed_stride(StrideA{}, make_shape(M, K, L));
  StrideB dB = cutlass::make_cute_packed_stride(StrideB{}, make_shape(N, K, L));
  StrideC dC = cutlass::make_cute_packed_stride(StrideC{}, make_shape(M, N, L));
  StrideD dD = cutlass::make_cute_packed_stride(StrideD{}, make_shape(M, N, L));
  LayoutSFA layout_SFA = Sm1xxBlkScaledConfig::tile_atom_to_shape_SFA(make_shape(M, N, K, L));
  LayoutSFB layout_SFB = Sm1xxBlkScaledConfig::tile_atom_to_shape_SFB(make_shape(M, N, K, L));

  Tensor tensor_a = make_tensor(recast_ptr<TmaInternalElementA>(ptr_A), make_layout(make_shape(M, K, L), dA));
  Tensor tensor_b = make_tensor(recast_ptr<TmaInternalElementB>(ptr_B), make_layout(make_shape(N, K, L), dB));
  Tensor tensor_sfa = make_tensor(ptr_SFA, layout_SFA);
  Tensor tensor_sfb = make_tensor(ptr_SFB, layout_SFB);

  Params params;
  params.tma_a = make_tma_copy(GmemTiledCopyA{}, tensor_a, SmemLayoutA{}(_, _, Int<0>{}),
                                make_shape(shape<0>(TileShape{}), shape<2>(TileShape{})), _1{});
  params.tma_b = make_tma_copy(GmemTiledCopyB{}, tensor_b, SmemLayoutB{}(_, _, Int<0>{}),
                                make_shape(shape<1>(TileShape{}), shape<2>(TileShape{})), _1{});
  params.tma_sfa = make_tma_copy<uint16_t>(GmemTiledCopySFA{}, tensor_sfa, SmemLayoutSFA{}(_, _, Int<0>{}),
                                            make_shape(shape<0>(TileShape{}), shape<2>(TileShape{})), _1{});
  params.tma_sfb = make_tma_copy<uint16_t>(GmemTiledCopySFB{}, tensor_sfb, SmemLayoutSFB{}(_, _, Int<0>{}),
                                            make_shape(shape<1>(TileShape{}), shape<2>(TileShape{})), _1{});
  params.layout_SFA = layout_SFA;
  params.layout_SFB = layout_SFB;
  params.ptr_C = ptr_C;
  params.dC = dC;
  params.ptr_D = ptr_D;
  params.dD = dD;
  params.M = M;
  params.N = N;
  params.K = K;
  params.L = L;
  params.alpha = alpha;
  params.beta = beta;
  params.tile_counter = tile_counter;
  return params;
}

//
// Kernel: 1 producer warp (TMA loads) + 1 consumer group of size(TiledMma) threads
// (MMA + direct-to-global epilogue), looping persistently over tiles via a global
// atomic counter.
//

constexpr int NumConsumerThreads = 256;  // == size(TiledMma{})
constexpr int NumProducerThreads = 32;
constexpr int NumThreadsPerBlock = NumProducerThreads + NumConsumerThreads;

static_assert(size(TiledMma{}) == NumConsumerThreads, "TiledMma thread count mismatch.");

// TMA tensor-map descriptors embedded in Params must be passed via a __grid_constant__ const
// kernel parameter -- this is a real CUDA requirement (see cutlass/device_kernel.h's
// CUTLASS_GRID_CONSTANT), not a style choice; without it the cp.async.bulk.tensor PTX the
// TMA copy lowers to cannot reliably read the descriptor.
__global__ __launch_bounds__(NumThreadsPerBlock) void nvfp4_gemm_kernel(__grid_constant__ const Params params) {
  // __align__(1024): matches alignas(1024) on SharedStorage::smem_A/smem_B (needed by the TMA
  // swizzle atom) -- that alignas only fixes the *offset* within the struct; without this, the
  // dynamic shared memory region's absolute base address is only guaranteed word-aligned,
  // which manifested as a "misaligned shared address" fault inside the TMA copy.
  extern __shared__ __align__(1024) char smem_raw[];
  SharedStorage& shared_storage = *reinterpret_cast<SharedStorage*>(smem_raw);

  int tiles_m = (params.M + size<0>(TileShape{}) - 1) / size<0>(TileShape{});
  int tiles_n = (params.N + size<1>(TileShape{}) - 1) / size<1>(TileShape{});
  int k_tile_count = params.K / size<2>(TileShape{});

  bool is_producer = threadIdx.x < NumProducerThreads;

  typename MainloopPipeline::Params pipeline_params;
  pipeline_params.role =
      is_producer ? MainloopPipeline::ThreadCategory::Producer : MainloopPipeline::ThreadCategory::Consumer;
  pipeline_params.is_leader = (threadIdx.x == 0);
  pipeline_params.num_consumers = NumConsumerThreads;
  // NOT NumProducerThreads: only one elected lane per k-tile actually calls
  // producer_acquire/arrive_and_expect_tx (see the `if (lane_predicate)` guard below), and
  // num_producers sets the mbarrier's required arrival count -- setting it to the full
  // producer-warp size (32) meant the barrier waited for 32 arrivals that never came, hanging
  // consumer_wait forever.
  pipeline_params.num_producers = 1;
  pipeline_params.transaction_bytes = TmaTransactionBytes;
  MainloopPipeline pipeline(shared_storage.pipeline_storage, pipeline_params, ClusterShape{});
  __syncthreads();

  PipelineState smem_pipe_write = cutlass::make_producer_start_state<MainloopPipeline>();
  PipelineState smem_pipe_read;

  // Problem-global tensors (built once; sliced per-tile below).
  Tensor mA_mkl = params.tma_a.get_tma_tensor(make_shape(params.M, params.K, params.L));
  Tensor mB_nkl = params.tma_b.get_tma_tensor(make_shape(params.N, params.K, params.L));
  Tensor mSFA_mkl = params.tma_sfa.get_tma_tensor(shape(params.layout_SFA));
  Tensor mSFB_nkl = params.tma_sfb.get_tma_tensor(shape(params.layout_SFB));

  Tensor gA_mkl = local_tile(mA_mkl, TileShape{}, make_coord(_, _, _), Step<_1, X, _1>{});
  Tensor gB_nkl = local_tile(mB_nkl, TileShape{}, make_coord(_, _, _), Step<X, _1, _1>{});
  Tensor gSFA_mkl = local_tile(mSFA_mkl, TileShape{}, make_coord(_, _, _), Step<_1, X, _1>{});
  Tensor gSFB_nkl = local_tile(mSFB_nkl, TileShape{}, make_coord(_, _, _), Step<X, _1, _1>{});

  TiledMma tiled_mma;

  for (;;) {
    __shared__ int s_tile_idx;
    if (threadIdx.x == 0) {
      s_tile_idx = atomicAdd(params.tile_counter, 1);
    }
    __syncthreads();
    int tile_idx = s_tile_idx;
    int total_tiles = tiles_m * tiles_n * params.L;
    if (tile_idx >= total_tiles) {
      break;
    }

    int l_coord = tile_idx / (tiles_m * tiles_n);
    int mn = tile_idx % (tiles_m * tiles_n);
    int m_coord = mn % tiles_m;
    int n_coord = mn / tiles_m;

    if (is_producer) {
      int lane_predicate = cute::elect_one_sync();
      if (lane_predicate) {
        Tensor sA = make_tensor(make_smem_ptr(shared_storage.tensors.smem_A.begin()), SmemLayoutA{});
        Tensor sB = make_tensor(make_smem_ptr(shared_storage.tensors.smem_B.begin()), SmemLayoutB{});
        Tensor sSFA = make_tensor(make_smem_ptr(shared_storage.tensors.smem_SFA.begin()), SmemLayoutSFA{});
        Tensor sSFB = make_tensor(make_smem_ptr(shared_storage.tensors.smem_SFB.begin()), SmemLayoutSFB{});

        auto block_tma_a = params.tma_a.get_slice(0);
        auto block_tma_b = params.tma_b.get_slice(0);
        auto block_tma_sfa = params.tma_sfa.get_slice(0);
        auto block_tma_sfb = params.tma_sfb.get_slice(0);

        Tensor gA = gA_mkl(_, _, m_coord, _, l_coord);
        Tensor gB = gB_nkl(_, _, n_coord, _, l_coord);
        Tensor gSFA = gSFA_mkl(_, _, m_coord, _, l_coord);
        Tensor gSFB = gSFB_nkl(_, _, n_coord, _, l_coord);

        Tensor tAgA = block_tma_a.partition_S(gA);
        Tensor tAsA = block_tma_a.partition_D(sA);
        Tensor tBgB = block_tma_b.partition_S(gB);
        Tensor tBsB = block_tma_b.partition_D(sB);
        Tensor tAgSFA = block_tma_sfa.partition_S(gSFA);
        Tensor tAsSFA = block_tma_sfa.partition_D(sSFA);
        Tensor tBgSFB = block_tma_sfb.partition_S(gSFB);
        Tensor tBsSFB = block_tma_sfb.partition_D(sSFB);

        CUTLASS_PRAGMA_NO_UNROLL
        for (int k_tile = 0; k_tile < k_tile_count; ++k_tile) {
          pipeline.producer_acquire(smem_pipe_write);

          using BarrierType = typename MainloopPipeline::ProducerBarrierType;
          BarrierType* tma_barrier = pipeline.producer_get_barrier(smem_pipe_write);
          int write_stage = smem_pipe_write.index();

          copy(params.tma_a.with(*tma_barrier), tAgA(_, _, _, k_tile), tAsA(_, _, _, write_stage));
          copy(params.tma_b.with(*tma_barrier), tBgB(_, _, _, k_tile), tBsB(_, _, _, write_stage));
          copy(params.tma_sfa.with(*tma_barrier), tAgSFA(_, _, _, k_tile), tAsSFA(_, _, _, write_stage));
          copy(params.tma_sfb.with(*tma_barrier), tBgSFB(_, _, _, k_tile), tBsSFB(_, _, _, write_stage));

          ++smem_pipe_write;
        }
      }
      __syncwarp();
    } else {
      int mma_thread_idx = threadIdx.x - NumProducerThreads;
      auto thread_mma = tiled_mma.get_thread_slice(mma_thread_idx);

      Tensor accum = partition_fragment_C(tiled_mma, TileShapeMN{});
      clear(accum);

      Tensor sA = make_tensor(make_smem_ptr(shared_storage.tensors.smem_A.begin()), SmemLayoutA{});
      Tensor sB = make_tensor(make_smem_ptr(shared_storage.tensors.smem_B.begin()), SmemLayoutB{});
      Tensor sSFA = make_tensor(make_smem_ptr(shared_storage.tensors.smem_SFA.begin()), SmemLayoutSFA{});
      Tensor sSFB = make_tensor(make_smem_ptr(shared_storage.tensors.smem_SFB.begin()), SmemLayoutSFB{});

      Tensor tCrA = thread_mma.partition_fragment_A(sA(_, _, Int<0>{}));
      Tensor tCrB = thread_mma.partition_fragment_B(sB(_, _, Int<0>{}));
      Tensor tCrSFA = partition_fragment_SFA(sSFA(_, _, Int<0>{}), thread_mma);
      Tensor tCrSFB = partition_fragment_SFB(sSFB(_, _, Int<0>{}), thread_mma);

      auto smem_tiled_copy_A = make_tiled_copy_A(SmemCopyAtomA{}, tiled_mma);
      auto smem_thr_copy_A = smem_tiled_copy_A.get_thread_slice(mma_thread_idx);
      Tensor tCsA = smem_thr_copy_A.partition_S(as_position_independent_swizzle_tensor(sA));
      Tensor tCrA_copy_view = smem_thr_copy_A.retile_D(tCrA);

      auto smem_tiled_copy_B = make_tiled_copy_B(SmemCopyAtomB{}, tiled_mma);
      auto smem_thr_copy_B = smem_tiled_copy_B.get_thread_slice(mma_thread_idx);
      Tensor tCsB = smem_thr_copy_B.partition_S(as_position_independent_swizzle_tensor(sB));
      Tensor tCrB_copy_view = smem_thr_copy_B.retile_D(tCrB);

      auto tile_shape_mnk = tile_shape(tiled_mma);
      auto smem_tiled_copy_SFA = make_tiled_copy_impl(SmemCopyAtomSFA{}, get_layoutSFA_TV(tiled_mma),
                                                       make_shape(size<0>(tile_shape_mnk), size<2>(tile_shape_mnk)));
      auto smem_thr_copy_SFA = smem_tiled_copy_SFA.get_thread_slice(mma_thread_idx);
      Tensor tCsSFA = smem_thr_copy_SFA.partition_S(as_position_independent_swizzle_tensor(sSFA));
      Tensor tCrSFA_copy_view = smem_thr_copy_SFA.retile_D(tCrSFA);

      auto smem_tiled_copy_SFB = make_tiled_copy_impl(SmemCopyAtomSFB{}, get_layoutSFB_TV(tiled_mma),
                                                       make_shape(size<1>(tile_shape_mnk), size<2>(tile_shape_mnk)));
      auto smem_thr_copy_SFB = smem_tiled_copy_SFB.get_thread_slice(mma_thread_idx);
      Tensor tCsSFB = smem_thr_copy_SFB.partition_S(as_position_independent_swizzle_tensor(sSFB));
      Tensor tCrSFB_copy_view = smem_thr_copy_SFB.retile_D(tCrSFB);

      auto K_BLOCK_MAX = size<2>(tCrA);

      int read_stage = smem_pipe_read.index();
      auto tCsA_stage = tCsA(_, _, _, read_stage);
      auto tCsB_stage = tCsB(_, _, _, read_stage);
      auto tCsSFA_stage = tCsSFA(_, _, _, read_stage);
      auto tCsSFB_stage = tCsSFB(_, _, _, read_stage);

      auto copy_kblock = [&](auto k_block) {
        copy(smem_tiled_copy_A, tCsA_stage(_, _, k_block), tCrA_copy_view(_, _, k_block));
        copy(smem_tiled_copy_B, tCsB_stage(_, _, k_block), tCrB_copy_view(_, _, k_block));

        using MMAOp = typename TiledMma::MMA_Op;
        fp4_shift_A(MMAOp{}, tCrA_copy_view(_, _, k_block));
        fp4_shift_B(MMAOp{}, tCrB_copy_view(_, _, k_block));

        copy(tCsSFA_stage(_, _, k_block), tCrSFA_copy_view(_, _, k_block));
        copy(tCsSFB_stage(_, _, k_block), tCrSFB_copy_view(_, _, k_block));
      };
      auto gemm_kblock = [&](auto k_block) {
        cute::gemm(tiled_mma, make_zip_tensor(tCrA(_, _, k_block), tCrSFA(_, _, k_block)),
                   make_zip_tensor(tCrB(_, _, k_block), tCrSFB(_, _, k_block)), accum);
      };

      pipeline.consumer_wait(smem_pipe_read);
      copy_kblock(_0{});
      int k_tile_count_remaining = k_tile_count;
      CUTLASS_PRAGMA_NO_UNROLL
      for (; k_tile_count_remaining > 1; --k_tile_count_remaining) {
        for_each(make_int_sequence<decltype(K_BLOCK_MAX)::value>{}, [&](auto k_block) {
          auto k_block_next = ((k_block + 1) == K_BLOCK_MAX) ? 0 : (k_block + 1);

          if (k_block == K_BLOCK_MAX - 1) {
            cutlass::arch::NamedBarrier::sync(thr_size(tiled_mma), cutlass::arch::ReservedNamedBarriers::Sm120MainloopBarrier);
            pipeline.consumer_release(smem_pipe_read);
            ++smem_pipe_read;
            read_stage = smem_pipe_read.index();
            tCsA_stage = tCsA(_, _, _, read_stage);
            tCsB_stage = tCsB(_, _, _, read_stage);
            tCsSFA_stage = tCsSFA(_, _, _, read_stage);
            tCsSFB_stage = tCsSFB(_, _, _, read_stage);
            pipeline.consumer_wait(smem_pipe_read);
          }

          copy_kblock(k_block_next);
          gemm_kblock(k_block);
        });
      }

      // Hoist out the last k_tile: no further prefetch/wait past the end of the
      // pipeline is needed since this is the last tile's data.
      for_each(make_int_sequence<decltype(K_BLOCK_MAX)::value>{}, [&](auto k_block) {
        auto k_block_next = ((k_block + 1) == K_BLOCK_MAX) ? 0 : (k_block + 1);

        if (k_block == K_BLOCK_MAX - 1) {
          cutlass::arch::NamedBarrier::sync(thr_size(tiled_mma), cutlass::arch::ReservedNamedBarriers::Sm120MainloopBarrier);
          pipeline.consumer_release(smem_pipe_read);
          ++smem_pipe_read;
        }

        if (k_block_next > 0) {
          copy_kblock(k_block_next);
        }
        gemm_kblock(k_block);
      });

      // Direct-to-global epilogue: D = alpha * accum + beta * C.
      Tensor mC = make_tensor(make_gmem_ptr(params.ptr_C), make_shape(params.M, params.N, params.L), params.dC);
      Tensor mD = make_tensor(make_gmem_ptr(params.ptr_D), make_shape(params.M, params.N, params.L), params.dD);
      Tensor gC = local_tile(mC(_, _, l_coord), TileShapeMN{}, make_coord(m_coord, n_coord));
      Tensor gD = local_tile(mD(_, _, l_coord), TileShapeMN{}, make_coord(m_coord, n_coord));
      Tensor tCgC = thread_mma.partition_C(gC);
      Tensor tCgD = thread_mma.partition_C(gD);

      CUTE_UNROLL
      for (int i = 0; i < size(accum); ++i) {
        ElementCompute c_val = static_cast<ElementCompute>(tCgC(i));
        ElementCompute d_val = params.alpha * accum(i) + params.beta * c_val;
        tCgD(i) = static_cast<ElementD>(d_val);
      }
    }
  }
}

//
// Host-side driver: allocate, initialize, launch, verify, benchmark.
//

template <typename Element, typename Layout>
void initialize_block(cutlass::TensorView<Element, Layout> view, uint64_t seed) {
  constexpr int bits = cutlass::sizeof_bits<Element>::value;
  double scope_max, scope_min;
  if constexpr (bits <= 6) {
    scope_max = 2;
    scope_min = -2;
  } else if constexpr (cute::is_same_v<Element, cutlass::float_ue4m3_t> || cute::is_same_v<Element, cutlass::float_ue8m0_t>) {
    scope_max = 4;
    scope_min = 1;
  } else {
    scope_max = 4;
    scope_min = -4;
  }
  cutlass::reference::host::TensorFillRandomUniform(view, seed, scope_max, scope_min, 0);
}

template <typename T>
auto make_iterator(T* ptr) {
  return cute::recast_ptr<T>(ptr);
}

int run(int m, int n, int k, int warmup_iters, int bench_iters) {
  LayoutSFA layout_sfa = Sm1xxBlkScaledConfig::tile_atom_to_shape_SFA(make_shape(m, n, k, 1));
  LayoutSFB layout_sfb = Sm1xxBlkScaledConfig::tile_atom_to_shape_SFB(make_shape(m, n, k, 1));
  StrideA layout_a = cutlass::make_cute_packed_stride(StrideA{}, make_shape(m, k, 1));
  StrideB layout_b = cutlass::make_cute_packed_stride(StrideB{}, make_shape(n, k, 1));
  StrideC layout_c = cutlass::make_cute_packed_stride(StrideC{}, make_shape(m, n, 1));
  StrideD layout_d = cutlass::make_cute_packed_stride(StrideD{}, make_shape(m, n, 1));

  cutlass::HostTensor<ElementA, cutlass::layout::PackedVectorLayout> block_a;
  cutlass::HostTensor<ElementB, cutlass::layout::PackedVectorLayout> block_b;
  cutlass::HostTensor<ElementSF, cutlass::layout::PackedVectorLayout> block_sfa;
  cutlass::HostTensor<ElementSF, cutlass::layout::PackedVectorLayout> block_sfb;
  cutlass::HostTensor<ElementC, cutlass::layout::PackedVectorLayout> block_c;
  cutlass::HostTensor<ElementD, cutlass::layout::PackedVectorLayout> block_d;
  cutlass::HostTensor<ElementD, cutlass::layout::PackedVectorLayout> block_ref_d;

  block_a.reset(cutlass::make_Coord(m * k));
  block_b.reset(cutlass::make_Coord(n * k));
  block_c.reset(cutlass::make_Coord(m * n));
  block_d.reset(cutlass::make_Coord(m * n));
  block_ref_d.reset(cutlass::make_Coord(m * n));
  block_sfa.reset(cutlass::make_Coord(size(filter_zeros(layout_sfa))));
  block_sfb.reset(cutlass::make_Coord(size(filter_zeros(layout_sfb))));

  initialize_block(block_a.host_view(), 2021);
  initialize_block(block_b.host_view(), 2022);
  initialize_block(block_c.host_view(), 2023);
  initialize_block(block_sfa.host_view(), 2024);
  initialize_block(block_sfb.host_view(), 2025);

  block_a.sync_device();
  block_b.sync_device();
  block_c.sync_device();
  block_sfa.sync_device();
  block_sfb.sync_device();

  float alpha = 1.0f, beta = 0.0f;

  cutlass::device_memory::allocation<int> tile_counter(1);
  CUDA_CHECK(cudaMemset(tile_counter.get(), 0, sizeof(int)));

  Params params = make_params(m, n, k, 1, block_a.device_data(), block_b.device_data(), block_sfa.device_data(),
                               block_sfb.device_data(), block_c.device_data(), block_d.device_data(), alpha, beta,
                               tile_counter.get());

  int smem_size = static_cast<int>(sizeof(SharedStorage));  // pipeline_storage is already a member
  CUDA_CHECK(cudaFuncSetAttribute(nvfp4_gemm_kernel, cudaFuncAttributeMaxDynamicSharedMemorySize, smem_size));

  cudaDeviceProp props;
  CUDA_CHECK(cudaGetDeviceProperties(&props, 0));
  int grid = props.multiProcessorCount;

  auto launch = [&]() {
    CUDA_CHECK(cudaMemset(tile_counter.get(), 0, sizeof(int)));
    nvfp4_gemm_kernel<<<grid, NumThreadsPerBlock, smem_size>>>(params);
  };

  launch();
  CUDA_CHECK(cudaDeviceSynchronize());

  // Correctness check against CUTLASS's generic (block-scaled) host reference GEMM --
  // the same reference-checking approach as src/nvfp4_gemm.cu.
  Tensor tensor_a = make_tensor(make_iterator(block_a.host_data()), make_layout(make_shape(m, k, 1), layout_a));
  Tensor tensor_sfa = make_tensor(block_sfa.host_data(), layout_sfa);
  Tensor tensor_b = make_tensor(make_iterator(block_b.host_data()), make_layout(make_shape(n, k, 1), layout_b));
  Tensor tensor_sfb = make_tensor(block_sfb.host_data(), layout_sfb);

  cutlass::reference::host::GettBlockScalingMainloopParams<ElementAccumulator, decltype(tensor_a), decltype(tensor_sfa),
                                                            decltype(tensor_b), decltype(tensor_sfb)>
      mainloop_params{tensor_a, tensor_sfa, tensor_b, tensor_sfb};

  auto tensor_c = make_tensor(make_iterator(block_c.host_data()), make_layout(make_shape(m, n, 1), layout_c));
  auto tensor_ref_d = make_tensor(make_iterator(block_ref_d.host_data()), make_layout(make_shape(m, n, 1), layout_d));

  cutlass::reference::host::GettBlockScalingEpilogueParams<ElementAccumulator, ElementAccumulator, ElementAccumulator,
                                                            decltype(tensor_c), decltype(tensor_ref_d)>
      epilogue_params{alpha, beta, tensor_c, tensor_ref_d};

  cutlass::reference::host::Gemm3x(mainloop_params, epilogue_params);

  block_d.sync_host();
  bool passed = cutlass::reference::host::TensorEquals(block_ref_d.host_view(), block_d.host_view());
  passed &= cutlass::reference::host::TensorNorm(block_ref_d.host_view()) > 0;
  passed &= cutlass::reference::host::TensorNorm(block_d.host_view()) > 0;

  std::cout << "Correctness: " << (passed ? "PASSED" : "FAILED") << std::endl;
  if (!passed) {
    return -1;
  }

  auto result = run_benchmark(launch, warmup_iters, bench_iters);

  double flops = 2.0 * double(m) * double(n) * double(k);
  double tflops = flops / (result.avg_runtime_ms / 1.0e3) / 1.0e12;

  std::cout << "Problem size: " << m << "x" << n << "x" << k << std::endl;
  std::cout << "Avg latency: " << result.avg_runtime_ms << " ms" << std::endl;
  std::cout << "Throughput: " << tflops << " TFLOP/s (nvfp4-cute)" << std::endl;

  return 0;
}

int main(int argc, char const** args) {
  cudaDeviceProp props;
  CUDA_CHECK(cudaGetDeviceProperties(&props, 0));

  if (!(props.major == 12 && (props.minor == 0 || props.minor == 1))) {
    std::cerr << "This kernel targets GeForce Blackwell (sm_120/121) block-scaled tensor cores; "
                 "detected compute capability "
              << props.major << "." << props.minor << std::endl;
    return 0;
  }

  int m = 4096, n = 4096, k = 4096;
  int warmup_iters = 10;
  int bench_iters = 50;

  if (argc >= 4) {
    m = std::atoi(args[1]);
    n = std::atoi(args[2]);
    k = std::atoi(args[3]);
  }
  if (argc >= 5) {
    bench_iters = std::atoi(args[4]);
  }

  return run(m, n, k, warmup_iters, bench_iters);
}
